"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Header_1 = require("./Header");
var Checkout = /** @class */ (function (_super) {
    __extends(Checkout, _super);
    function Checkout(props) {
        var _this = _super.call(this, props) || this;
        console.log(props);
        _this.state = { isLoaded: false, error: null, subtotal: props.match.params.subtotal, total: props.match.params.total, delivery: props.match.params.delivery };
        return _this;
    }
    Checkout.prototype.render = function () {
        return (React.createElement("main", { id: "main" },
            React.createElement("div", null,
                React.createElement(Header_1.Header, null),
                React.createElement("div", { className: "hero-wrap hero-bread", style: { backgroundImage: "url('images/background.jpg')" } },
                    React.createElement("div", { className: "container" },
                        React.createElement("div", { className: "row no-gutters slider-text align-items-center justify-content-center" },
                            React.createElement("div", { className: "col-md-9 text-center" },
                                React.createElement("h1", { className: "mb-0 bread" }, "Checkout"))))),
                React.createElement("section", { className: "ftco-section" },
                    React.createElement("div", { className: "container" },
                        React.createElement("div", { className: "row justify-content-center" },
                            React.createElement("div", { className: "col-xl-10" },
                                React.createElement("form", { action: "#", className: "billing-form" },
                                    React.createElement("h3", { className: "mb-4 billing-heading" }, "Billing Details"),
                                    React.createElement("div", { className: "row align-items-end" },
                                        React.createElement("div", { className: "col-md-6" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("label", { htmlFor: "firstname" }, "Firt Name"),
                                                React.createElement("input", { type: "text", className: "form-control", placeholder: "" }))),
                                        React.createElement("div", { className: "col-md-6" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("label", { htmlFor: "lastname" }, "Last Name"),
                                                React.createElement("input", { type: "text", className: "form-control", placeholder: "" }))),
                                        React.createElement("div", { className: "w-100" }),
                                        React.createElement("div", { className: "col-md-12" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("label", { htmlFor: "country" }, "State / Country"),
                                                React.createElement("div", { className: "select-wrap" },
                                                    React.createElement("div", { className: "icon" },
                                                        React.createElement("span", { className: "ion-ios-arrow-down" })),
                                                    React.createElement("select", { name: "", id: "", className: "form-control" },
                                                        React.createElement("option", { value: "GB" }, "United Kingdom"),
                                                        React.createElement("option", { value: "AL" }, "Albania"),
                                                        React.createElement("option", { value: "AD" }, "Andorra"),
                                                        React.createElement("option", { value: "AT" }, "Austria"),
                                                        React.createElement("option", { value: "BY" }, "Belarus"),
                                                        React.createElement("option", { value: "BE" }, "Belgium"),
                                                        React.createElement("option", { value: "BA" }, "Bosnia and Herzegovina"),
                                                        React.createElement("option", { value: "BG" }, "Bulgaria"),
                                                        React.createElement("option", { value: "HR" }, "Croatia (Hrvatska)"),
                                                        React.createElement("option", { value: "CY" }, "Cyprus"),
                                                        React.createElement("option", { value: "CZ" }, "Czech Republic"),
                                                        React.createElement("option", { value: "FR" }, "France"),
                                                        React.createElement("option", { value: "GI" }, "Gibraltar"),
                                                        React.createElement("option", { value: "DE" }, "Germany"),
                                                        React.createElement("option", { value: "GR" }, "Greece"),
                                                        React.createElement("option", { value: "VA" }, "Holy See (Vatican City State)"),
                                                        React.createElement("option", { value: "HU" }, "Hungary"),
                                                        React.createElement("option", { value: "IT" }, "Italy"),
                                                        React.createElement("option", { value: "LI" }, "Liechtenstein"),
                                                        React.createElement("option", { value: "LU" }, "Luxembourg"),
                                                        React.createElement("option", { value: "MK" }, "Macedonia"),
                                                        React.createElement("option", { value: "MT" }, "Malta"),
                                                        React.createElement("option", { value: "MD" }, "Moldova"),
                                                        React.createElement("option", { value: "MC" }, "Monaco"),
                                                        React.createElement("option", { value: "ME" }, "Montenegro"),
                                                        React.createElement("option", { value: "NL" }, "Netherlands"),
                                                        React.createElement("option", { value: "PL" }, "Poland"),
                                                        React.createElement("option", { value: "PT" }, "Portugal"),
                                                        React.createElement("option", { value: "RO" }, "Romania"),
                                                        React.createElement("option", { value: "SM" }, "San Marino"),
                                                        React.createElement("option", { value: "RS" }, "Serbia"),
                                                        React.createElement("option", { value: "SK" }, "Slovakia"),
                                                        React.createElement("option", { value: "SI" }, "Slovenia"),
                                                        React.createElement("option", { value: "ES" }, "Spain"),
                                                        React.createElement("option", { value: "UA" }, "Ukraine"),
                                                        React.createElement("option", { value: "DK" }, "Denmark"),
                                                        React.createElement("option", { value: "EE" }, "Estonia"),
                                                        React.createElement("option", { value: "FO" }, "Faroe Islands"),
                                                        React.createElement("option", { value: "FI" }, "Finland"),
                                                        React.createElement("option", { value: "GL" }, "Greenland"),
                                                        React.createElement("option", { value: "IS" }, "Iceland"),
                                                        React.createElement("option", { value: "IE" }, "Ireland"),
                                                        React.createElement("option", { value: "LV" }, "Latvia"),
                                                        React.createElement("option", { value: "LT" }, "Lithuania"),
                                                        React.createElement("option", { value: "NO" }, "Norway"),
                                                        React.createElement("option", { value: "SJ" }, "Svalbard and Jan Mayen Islands"),
                                                        React.createElement("option", { value: "SE" }, "Sweden"),
                                                        React.createElement("option", { value: "CH" }, "Switzerland"),
                                                        React.createElement("option", { value: "TR" }, "Turkey"))))),
                                        React.createElement("div", { className: "w-100" }),
                                        React.createElement("div", { className: "col-md-6" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("label", { htmlFor: "streetaddress" }, "Street Address"),
                                                React.createElement("input", { type: "text", className: "form-control", placeholder: "House number and street name" }))),
                                        React.createElement("div", { className: "col-md-6" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("input", { type: "text", className: "form-control", placeholder: "Appartment, suite, unit etc: (optional)" }))),
                                        React.createElement("div", { className: "w-100" }),
                                        React.createElement("div", { className: "col-md-6" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("label", { htmlFor: "towncity" }, "Town / City"),
                                                React.createElement("input", { type: "text", className: "form-control", placeholder: "" }))),
                                        React.createElement("div", { className: "col-md-6" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("label", { htmlFor: "postcodezip" }, "Postcode / ZIP *"),
                                                React.createElement("input", { type: "text", className: "form-control", placeholder: "" }))),
                                        React.createElement("div", { className: "w-100" }),
                                        React.createElement("div", { className: "col-md-6" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("label", { htmlFor: "phone" }, "Phone"),
                                                React.createElement("input", { type: "text", className: "form-control", placeholder: "" }))),
                                        React.createElement("div", { className: "col-md-6" },
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("label", { htmlFor: "emailaddress" }, "Email Address"),
                                                React.createElement("input", { type: "text", className: "form-control", placeholder: "" }))),
                                        React.createElement("div", { className: "w-100" }),
                                        React.createElement("div", { className: "col-md-12" },
                                            React.createElement("div", { className: "form-group mt-4" },
                                                React.createElement("div", { className: "radio" },
                                                    React.createElement("label", { className: "mr-3" },
                                                        React.createElement("input", { type: "radio", name: "optradio" }),
                                                        " Create an Account? "),
                                                    React.createElement("label", null,
                                                        React.createElement("input", { type: "radio", name: "optradio" }),
                                                        " Ship to different address")))))),
                                React.createElement("div", { className: "row mt-5 pt-3 d-flex" },
                                    React.createElement("div", { className: "col-md-6 d-flex" },
                                        React.createElement("div", { className: "cart-detail cart-total bg-light p-3 p-md-4" },
                                            React.createElement("h3", { className: "billing-heading mb-4" }, "Cart Total"),
                                            React.createElement("p", { className: "d-flex" },
                                                React.createElement("span", null, "Subtotal"),
                                                React.createElement("span", null,
                                                    "$",
                                                    this.state.subtotal)),
                                            React.createElement("p", { className: "d-flex" },
                                                React.createElement("span", null, "Delivery"),
                                                React.createElement("span", null,
                                                    "$",
                                                    this.state.delivery)),
                                            React.createElement("hr", null),
                                            React.createElement("p", { className: "d-flex total-price" },
                                                React.createElement("span", null, "Total"),
                                                React.createElement("span", null,
                                                    "$",
                                                    this.state.total)))),
                                    React.createElement("div", { className: "col-md-6" },
                                        React.createElement("div", { className: "cart-detail bg-light p-3 p-md-4" },
                                            React.createElement("h3", { className: "billing-heading mb-4" }, "Payment Method"),
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("div", { className: "col-md-12" },
                                                    React.createElement("div", { className: "radio" },
                                                        React.createElement("label", null,
                                                            React.createElement("input", { type: "radio", name: "optradio", className: "mr-2" }),
                                                            " Direct Bank Tranfer")))),
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("div", { className: "col-md-12" },
                                                    React.createElement("div", { className: "radio" },
                                                        React.createElement("label", null,
                                                            React.createElement("input", { type: "radio", name: "optradio", className: "mr-2" }),
                                                            " Check Payment")))),
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("div", { className: "col-md-12" },
                                                    React.createElement("div", { className: "radio" },
                                                        React.createElement("label", null,
                                                            React.createElement("input", { type: "radio", name: "optradio", className: "mr-2" }),
                                                            " Paypal")))),
                                            React.createElement("div", { className: "form-group" },
                                                React.createElement("div", { className: "col-md-12" },
                                                    React.createElement("div", { className: "checkbox" },
                                                        React.createElement("label", null,
                                                            React.createElement("input", { type: "checkbox", value: "", className: "mr-2" }),
                                                            " I have read and accept the terms and conditions")))),
                                            React.createElement("p", null,
                                                React.createElement("a", { href: "#", className: "btn btn-primary py-3 px-4" }, "Place an order"))))))))))));
    };
    return Checkout;
}(React.Component));
exports.Checkout = Checkout;
//# sourceMappingURL=PageCheckout.js.map