"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Header_1 = require("./Header");
var Translate = require("react-translate-component");
var sfcookies_1 = require("sfcookies");
var PrivacyPolicy = /** @class */ (function (_super) {
    __extends(PrivacyPolicy, _super);
    function PrivacyPolicy(props) {
        var _this = _super.call(this, props) || this;
        _this.reloadPage = _this.reloadPage.bind(_this);
        return _this;
    }
    PrivacyPolicy.prototype.reloadPage = function () {
        window.location.reload(false);
    };
    PrivacyPolicy.prototype.render = function () {
        var lang = sfcookies_1.read_cookie('lang');
        return (React.createElement("div", null,
            React.createElement("main", { id: "main" },
                React.createElement("div", null,
                    React.createElement(Header_1.Header, { reloadPage: this.reloadPage }),
                    React.createElement("section", { className: "ftco-section contact-section bg-light" },
                        React.createElement("div", { className: "container" },
                            React.createElement("div", { className: "bg-white p-3", style: { textAlign: 'justify' } },
                                React.createElement("div", { className: "row justify-content-center mb-3 pb-3" },
                                    React.createElement("div", { className: "col-md-12 heading-section text-center" },
                                        React.createElement("h3", { className: "mb-4" },
                                            React.createElement(Translate, { content: 'privacyPolicy.Title' })))),
                                lang == 'ro' &&
                                    React.createElement("div", null,
                                        React.createElement("p", null, "Aplic\u00E2nd cerin\u021Bele legilor \u00EEn vigoare nr. 677/2001 \u0219i 506/2014 privind protec\u021Bia persoanelor cu privire la prelucrarea datelor cu caracter personal \u0219i protec\u021Bia vie\u021Bii private \u00EEn sectorul comunica\u021Biilor electronice. Proprietarul, Gabriel Habet SRL av\u00E2nd sediul social \u00EEn Jude\u021Bul Ia\u0219i, Sat \u021Aig\u0103na\u0219i, Comuna \u021Aig\u0103na\u0219i, Strada Principal\u0103, Nr. 126 cu num\u0103r de ordine \u00EEn Registrul Comer\u021Bului J22/2726/2019, cod unic de \u00EEnregistrare fiscal\u0103 RO41533477 are obliga\u021Bia de a administra \u00EEn condi\u021Bii de siguran\u021B\u0103 \u0219i numai \u00EEn scopuri precis specificate datele dumeavoastr\u0103 personale pe care le furniza\u021Bi \u00EEn momentul realiz\u0103ri comenzilor."),
                                        React.createElement("p", null,
                                            "Clientul nu este obligat s\u0103 furnizeze datele cerute, dar acest lucru fiind totu\u0219i necesar pentru finalizarea comenzii \u0219i plasarea de noi oferte \u0219i reduceri din partea magazinului nostru. \u00CEn cazul \u00EEn care refuza\u021Bi s\u0103 furniza\u021Bi aceste date, apare imposibilitatea proces\u0103rii \u0219i livr\u0103rii comenzilor c\u0103tre client, lucru ce opre\u0219te comand\u0103 dumneavoastr\u0103. Modificarea sau \u0219tergerea datelor personale este garantat\u0103 conform legii nr. 677/2001, iar accesul asupra acestor modific\u0103ri este realizat pe baza de user \u0219i parol\u0103 predate \u00EEn momentul realiz\u0103rii contului. Drepturile de opunere asupra prelucr\u0103rii datelor dumneavoastr\u0103 sunt la fel garantate prin lege, iar solicitarea \u0219tergerii datelor este realizat\u0103 de c\u0103tre Proprietar, printr-o cerere \u00EEnregistrat\u0103.",
                                            React.createElement("br", null),
                                            "\u00CEn momentul \u00EEn care unele din datele dumeavoastr\u0103 sunt incorecte va rug\u0103m s\u0103 ne anun\u021Ba\u021Bi imediat prin orice mijloc de comunicare posibil. "),
                                        React.createElement("h5", null, "Politic\u0103 de confiden\u021Bialitate GDPR cu privire la prelucrarea datelor cuprinde urm\u0103toarele informa\u021Bii:"),
                                        React.createElement("h5", null, "1.\tCe reprezint\u0103 datele cu caracter general?"),
                                        React.createElement("p", null, "Datele cu caracter personal, sunt datele pe care, de regul\u0103 le colect\u0103m direct de la dumneavoastr\u0103 astfel \u00EEnc\u00E2t s\u0103 ave\u021Bi controlul asupra informa\u021Biilor pe care ni le oferi\u021Bi."),
                                        React.createElement("p", null,
                                            "De exemplu, primim informa\u021Bii de la dumneavoastr\u0103 astfel:",
                                            React.createElement("br", null),
                                            "Atunci c\u00E2nd v\u0103 crea\u021Bi un cont pe site-ul nostru www.gabrielhabet.com, ne transmite\u021Bi: adresa de e-mail.",
                                            React.createElement("br", null),
                                            "\u00CEn sec\u021Biunea dumneavoastr\u0103 personal\u0103 (Contul meu) ave\u021Bi posibilitatea s\u0103 ad\u0103uga\u021Bi informa\u021Bii suplimentare cum ar fi: numele, prenumele, num\u0103r de telefon, adrese de livrare.",
                                            React.createElement("br", null),
                                            "\u00CEn momentul c\u00E2nd plasa\u021Bi o comand\u0103, ne furniza\u021Bi informa\u021Bii precum: produsul dorit, numele \u0219i prenumele, adresa de livrare, detalii de facturare, metod\u0103 de plat\u0103, num\u0103r de telefon, datele cardului bancar etc."),
                                        React.createElement("h5", null, "2.\tCe tipuri de date cu caracter personal colect\u0103m?"),
                                        React.createElement("p", null, "Colect\u0103m urm\u0103roarele date cu caracter personal pentru anumite scopuri \u0219i servicii cum ar fi:"),
                                        "-",
                                        React.createElement("b", null, "nume \u0219i prenume:"),
                                        " pentru a putea realiza livrarea produselor comandate, avem nevoie de aceste date;",
                                        React.createElement("br", null),
                                        "- ",
                                        React.createElement("b", null, "e-mail:"),
                                        " pentru a realiza o comunicare \u00EEntre platforma \u0219i user, adresa de e-mail o folosim pentru a v\u0103 confirm\u0103 comand\u0103 \u0219i pentru a v\u0103 informa despre stadiul comenzilor;",
                                        React.createElement("br", null),
                                        "- ",
                                        React.createElement("b", null, "num\u0103r de telefon:"),
                                        " avem nevoie de num\u0103rul de telefon pentru confirmarea comenzii \u0219i pentru a stabili \u0219i alte detalii legate de comand\u0103 plasat\u0103.",
                                        React.createElement("br", null),
                                        "- ",
                                        React.createElement("b", null, "adresa de livrare:"),
                                        " pentru a reu\u0219i s\u0103 livr\u0103m comand\u0103, avem nevoie de comunicarea adresei corecte, \u00EEn procesul de comand\u0103",
                                        React.createElement("br", null),
                                        "- ",
                                        React.createElement("b", null, "adresa de facturare:"),
                                        " pentru a reu\u0219i s\u0103 facem factur\u0103 fiscal\u0103, avem nevoie de comunicare corect\u0103 a datelor de facturare",
                                        React.createElement("br", null),
                                        "- ",
                                        React.createElement("b", null, "prelucrarea comenzilor \u0219i solu\u021Bionarea lor:"),
                                        " prelucrarea, validarea, solu\u021Bionare sau anularea comenzilor \u0219i/sau a bunurilor \u0219i serviciilor achizi\u021Bionate.",
                                        React.createElement("br", null),
                                        "- ",
                                        React.createElement("b", null, "rambursarea banilor:"),
                                        " contravaloarea produselor conform prevederilor legalee existente",
                                        React.createElement("br", null),
                                        "- ",
                                        React.createElement("b", null, "rambursarea produselor:"),
                                        " returnarea produselor conform prevederilor legale existente",
                                        React.createElement("h5", null, "3.\tCare este scopul \u0219i temeiul prelucr\u0103rii datelor \u0219i cum folosim informa\u021Biile tale personale ?"),
                                        React.createElement("p", null,
                                            "Datele pe care \"user/clientul\" ni le oferi voluntar, cele pe care le trimite prin plasarea unei comenzi \u00EEn temeiul legal este acela de a face demersuri la cererea persoanei vizate \u00EEnainte de \u00EEncheierea unui contract (art. 6 alin. (1) lit. b din Regulamentul (UE) 679/2016).",
                                            React.createElement("br", null),
                                            "Aceste date, le folosim pentru a reu\u0219i s\u0103 emite factur\u0103 fiscal\u0103 \u0219i s\u0103 face livrarea corect\u0103 \u0219i corespunz\u0103toare a produselor."),
                                        React.createElement("p", null, "\u00CEn acest sens, ne asigur\u0103m \u00EEntotdeauna c\u0103 aceste prelucr\u0103ri sunt efectuate cu respectarea drepturilor \u0219i libert\u0103\u021Bilor dumneavoastr\u0103, iar deciziile luate pe baza acestora nu au efecte legale asupra dumneavoastr\u0103 \u0219i nu v\u0103 afecteaz\u0103 similar \u00EEntr-o m\u0103sur\u0103 semnificativ\u0103. Comunic\u0103rile de marketing sunt transmise pe consim\u021B\u0103m\u00E2ntul dumneavoastr\u0103 prealabil. "),
                                        React.createElement("p", null,
                                            "De asemenea, v\u0103 pute\u021Bi r\u0103zg\u00E2ndi \u0219i retrage consim\u021B\u0103m\u00E2ntul \u00EEn orice moment, prin:",
                                            React.createElement("br", null),
                                            "- Modificarea set\u0103rilor din contul de client;",
                                            React.createElement("br", null),
                                            "- Dezabonarea de la mesajel/email-urile pe care le primi\u021Bi de la noi;",
                                            React.createElement("br", null),
                                            "- Contactarea gabrielhabet.com.",
                                            React.createElement("br", null)),
                                        React.createElement("p", null, "Sunt \u0219i anumite situa\u021Bii \u00EEn care ne desf\u0103\u0219ur\u0103m activit\u0103\u021Bile de marketing pe interesul nostru legitim de a ne promova \u0219i dezvolt\u0103 activitatea comercial\u0103, conform Legii nr 506/2004, Art.12 (2). \u00CEn situa\u021Biile de a\u0219a natur\u0103, unde folosim informa\u021Bii cu privire la dumneavoastr\u0103 pentru un interes legitim al nostru, avem \u00EEn vedere s\u0103 lu\u0103m toate m\u0103surile necesare pentru c\u0103 drepturile \u0219i libert\u0103\u021Bile dumneavoastr\u0103 fundamentale s\u0103 nu fie afectate."),
                                        React.createElement("h5", null, "4.\tCare este temeiul legal prin care colect\u0103m aceste date personale ?"),
                                        React.createElement("p", null, "Temeiul legal este acela de a face demersuri la cererea persoanei vizate prin accesare, \u00EEnainte de \u00EEncheierea unui contract (art. 6 alin. (1) lit. b din Regulamentul (UE) 679/2016)."),
                                        React.createElement("p", null, "Datele pe care le colect\u0103m automat prin folosirea cookie-urilor sau a altor tehnologii similare, temeiul pentru prelucrare este consim\u021B\u0103m\u00E2ntul. Odat\u0103 cu accesarea site-ului, \u00EE\u021Bi dai \u00EEn mod valabil consim\u021B\u0103m\u00E2ntul asupra prelucr\u0103rii informa\u021Biilor necesare pentru utilizare."),
                                        React.createElement("h5", null, "5.\tPartajarea datelor cu caracter personal."),
                                        React.createElement("p", null, "\u00CEn func\u021Bie de cazul care se impune, putem transmite sau oferi acces la anumite date cu caracter personal ale dumneavoastr\u0103, urm\u0103toarelor categorii de destinatari: firmelor de curierat DPD \u0219i Fan Curier care asigur\u0103 expedi\u021Bia produselor comandate. De asemenea, exist\u0103 \u0219i cazul \u00EEn care pentru a ne ap\u0103ra un interes legitim, putem de asemenea divulg\u0103 anumite date cu caracter personal unor autorit\u0103\u021Bi publice. \u00CEn acest sens, ne asigur\u0103m c\u0103 accesul la datele dumneavoastr\u0103 de c\u0103tre ter\u021Bii persoane juridice de drept privat este realizat, \u00EEn baza unor contracte \u00EEncheiate cu ace\u0219tia, a\u0219a cum specific\u0103 legea privind protec\u021Bia datelor \u0219i confiden\u021Bialitatea informa\u021Biilor."),
                                        React.createElement("h5", null, "6.\tPerioada de reten\u021Bie a datelor cu caracter personal?"),
                                        React.createElement("p", null,
                                            "Datele cu caracter personal sunt stocate c\u00E2t timp contul de pe gabrielhabet.com este activ. Bine\u00EEn\u021Beles, ne pute\u021Bi solicit\u0103 \u0219tergerea anumitor date, ori \u00EEnchiderea contului, \u00EEn func\u021Bie de preferin\u021Bele dumneavoastr\u0103. \u00CEn cazul comenzilor plasate pe www.gabrielhabet.com datele dumneavoastr\u0103 personale, dintre cele care sunt cuprinse \u00EEn documentele financiar-contabile sau \u00EEn documente anexate acestora, vor fi p\u0103strate 10 ani conform dispozi\u021Biilor art. 38 din Anex\u0103 1 la Ordinul nr. 2634/2015 privind documentele financiar-contabile, emis de Ministerul Finan\u021Belor Publice.",
                                            React.createElement("br", null),
                                            "Implicit, nu vor fi accesate \u00EEn niciun alt scop dec\u00E2t scopul legal pentru care au fost arhivate. Dup\u0103 termenul de 10 ani, aceste date vor fi distruse."),
                                        React.createElement("h5", null, "7.\tDrepturile persoanei vizate de colectarea datelor personale."),
                                        React.createElement("p", null,
                                            "Regulamentul general privind protec\u021Bia datelor v\u0103 recunoa\u0219te o serie drepturi \u00EEn ceea ce prive\u0219te utilizarea datelor dumneavoastr\u0103 cu caracter personal. ",
                                            React.createElement("br", null),
                                            "Pute\u021Bi solicit\u0103 accesul la datele dumneavoastr\u0103, corectarea gre\u0219elilor din fi\u0219ierele noastre (dac\u0103 exist\u0103) \u0219i/sau v\u0103 pute\u021Bi opune la prelucrarea datelor dumneavoastr\u0103 cu caracter personal. De asemenea, ave\u021Bi dreptul de a v\u0103 pl\u00E2nge autorit\u0103\u021Bii de supraveghere competen\u021Be sau de a v\u0103 adresa justi\u021Biei. Dup\u0103 caz, pute\u021Bi beneficia \u0219i de dreptul de a solicit\u0103 \u0219tergerea datelor dumneavoastr\u0103 cu caracter personal, dreptul la restric\u021Bionarea prelucr\u0103rii datelor dumneavoastr\u0103 \u0219i dreptul la portabilitatea datelor. O listare a fiec\u0103rui drept \u00EEl pute\u021Bi consulta mai jos:",
                                            React.createElement("br", null)),
                                        "- accesul la datele personale",
                                        React.createElement("br", null),
                                        "- rectificare informa\u021Biilor sau a datele personale",
                                        React.createElement("br", null),
                                        "- \u0219tergerea datelor personale sau a informa\u021Biilor. Realizarea acestui drept, aduce cu sine \u0219i eliminarea tuturor informa\u021Biilor despre user iar gabrielhabet.com nu este vinovat de pierderile suferite de user.",
                                        React.createElement("br", null),
                                        "- restric\u021Bionarea datelor cu caracter personal",
                                        React.createElement("br", null),
                                        "- portabilitatea sau opozi\u021Bia datelor cu caracter personal",
                                        React.createElement("br", null),
                                        "- depunerea depl\u00E2nge la autoritatea de supraveghere",
                                        React.createElement("h5", null, "8.\tPolitic\u0103 de utilizare a cookies-urilor."),
                                        React.createElement("p", null, " A\u0219a cum la r\u00E2ndul nostru, suntem clien\u021Bi online, apreciem \u0219i respect\u0103m importan\u021Ba confiden\u021Bialit\u0103\u021Bii \u0219i securit\u0103\u021Bii datelor de pe internet. gabrielhabet.com stocheaz\u0103 \u0219i prelucreaz\u0103 datele cu caracter personal, \u00EEn conformitate cu Legea privind protec\u021Bia datelor cu caracter personal"),
                                        React.createElement("p", null,
                                            "Mai multe detalii despre cookies \u0219i modalitatea lor de folosire, pute\u021Bi s\u0103 citi\u021Bi: ",
                                            React.createElement("a", { href: "/#/cookie_policy", title: "Cookies" }, "AICI")),
                                        React.createElement("h5", null, "9.\tCum ne po\u021Bi contacta?"),
                                        React.createElement("p", null, "Dac\u0103 e\u0219ti \u00EEn situa\u021Bia \u00EEn care ai de adresat vreo \u00EEntrbare cu privire la podusele noastre, ne po\u021Bi contacta prin intermediul formularului de contact de pe site-ul nostru: https://www.gabrielhabet.com/contact, iar noi \u00EE\u021Bi vom r\u0103spunde \u00EEn cel mai scurt timp. "),
                                        React.createElement("p", null, "De asemenea ai la dispozi\u021Bie num\u0103rul de telefon: +40 753 696 163 , ori adesa de email: contact@gabrielhabet.com pentru \u00EEntreb\u0103rile extra. "),
                                        React.createElement("p", null, "Pagin\u0103 de facebook: https://www.facebook.com/butterflygabrielhabet \u00EE\u021Bi st\u0103, de asemenea, la dispozi\u021Bie pentru a rezolva cu eficien\u021B\u0103 orice neclaritate ai mai avea. \u021Aine minte, de luni p\u00E2n\u0103 vineri, \u00EEntre orele 09:00 \u2013 17:00 ne po\u021Bi adresa \u00EEntreb\u0103rile tale, iar noi cu pl\u0103cere \u00EE\u021Bi vom r\u0103spunde."),
                                        React.createElement("h5", null, "Politic\u0103 de confiden\u021Bialitate GDPR cu privire la prelucrarea datelor."),
                                        React.createElement("p", null),
                                        React.createElement("p", null,
                                            React.createElement("a", { href: "https://eur-lex.europa.eu/legal-content/RO/TXT/PDF/?uri=CELEX:32016R0679&from=RO", target: "_blank" }, "Regulamentul (UE) 2016/679"),
                                            " al Parlamentului European \u0219i al Consiliului din 27 aprilie 2016 privind protec\u021Bia persoanelor fizice \u00EEn ceea ce prive\u0219te prelucrarea datelor cu caracter personal \u0219i privind liber\u0103 circula\u021Bie a acestora. gabrielhabet.com consider\u0103 asigurarea dreptului la protec\u021Bia datelor cu caracter personal c\u0103 un angajament fundamental \u00EEn colaborarea noastr\u0103 \u0219i respect\u0103 regulamentul UE.",
                                            React.createElement("br", null),
                                            " Vom \u00EEncerca s\u0103 depunem toate eforturile necesare pentru a preleva \u0219i prelucra datele personale ale utilizatorilor \u00EEn deplin\u0103 sigurata. Pentru c\u0103 dorim o transparent total\u0103 \u00EEn acest angajament, am preg\u0103tit aceast\u0103 pagin\u0103 ",
                                            React.createElement("a", { href: "https://www.gabrielhabet/#/privacy_policy" }, "GDPR - Politic\u0103 de confiden\u021Bialitate"),
                                            ", pentru a prezen\u021Ba toate informa\u021Biile c\u00E2t mai detaliat \u0219i transparent, dup\u0103 cum urmeaz\u0103:"),
                                        React.createElement("div", null,
                                            React.createElement("h5", null,
                                                React.createElement("b", null, "Cine suntem \u0219i cum putem fi contacta\u021Bi:")),
                                            React.createElement("div", null,
                                                "- gabrielhabet.com este un magazin online www.gabrielhabet.com de\u021Binut de firma GABRIEL HABET SRL, \u00EEn calitate de persoan\u0103 juridic\u0103 CUI: RO41533477, J22/2726/2019 cu domeniul de activitate \u00EEn comer\u021Bul online. \u00CEn angajamentul de colaborare, Gabriel Habet, reprezint\u0103 un operator atunci c\u00E2nd prelucreaz\u0103 datele dumneavostr\u0103 cu caracter personal.",
                                                React.createElement("br", null),
                                                " - Pentru orice informa\u021Bii suplimentare despre GDPR sau calitatea de operator \u00EEn prelucrarea datelor dumneavostr\u0103 personale, va rug\u0103m s\u0103 ne contacta\u021Bi peadresa de e-mail: contact@gabrielhabet.com sau telefonic la num\u0103rul: +40 753 696 163"),
                                            React.createElement("h5", null,
                                                React.createElement("b", null, "Ce informa\u021Bii \u0219i date cu caracter personal p\u0103str\u0103m \u0219i prelucr\u0103m despre dumneavoastr\u0103:")),
                                            React.createElement("p", null, "Aceste date cu caracter personal, sunt de regul\u0103 colectate direct de la utilizator, astfel \u00EEnc\u00E2t ave\u021Bi controlul total sau par\u021Bial (acolo unde tehnic\u0103 nu ne permite) asupra tipurilor de informa\u021Bii oferite. "))),
                                lang == 'en' &&
                                    React.createElement("div", null,
                                        React.createElement("p", null, " Applying the requirements of the laws in force no. 677/2001 and 506/2014 on the protection of individuals with regard to the processing of personal data and the protection of privacy in the electronic communications sector. The owner, Gabriel Habet SRL having its registered office in Ia\u0219i County, \u021Aig\u0103na\u0219i Village, \u021Aig\u0103na\u0219i Commune, Main Street, Nr. 126 with serial number in the Trade Register J22 / 2726/2019, unique fiscal registration code RO41533477 has the obligation to manage in safe conditions and only for precisely specified purposes your personal data that you provide when placing orders. "),
                                        React.createElement("p", null,
                                            " The customer is not obliged to provide the required data, but this is still necessary to complete the order and place new offers and discounts from our store. If you refuse to provide this data, it is impossible to process and deliver orders to the customer, which stops your order. The modification or deletion of personal data is guaranteed according to law no. 677/2001, and access to these changes is based on the user and password provided at the time of account creation. The rights to oppose the processing of your data are also guaranteed by law, and the request for deletion of data is made by the Owner, through a registered request. ",
                                            React.createElement("br", null),
                                            "If any of your data is incorrect, please notify us immediately by any possible means of communication. "),
                                        React.createElement("h5", null, " GDPR's privacy policy regarding data processing includes the following information: "),
                                        React.createElement("h5", null, " 1. What is general data? "),
                                        React.createElement("p", null, " Personal data is data that we usually collect directly from you so that you have control over the information you provide to us. "),
                                        React.createElement("p", null,
                                            " For example, we receive information from you as follows: ",
                                            React.createElement("br", null),
                                            "When you create an account on our website www.gabrielhabet.com, send us: e-mail address. ",
                                            React.createElement("br", null),
                                            "In your personal section (My account) you can add additional information such as: name, surname, telephone number, delivery addresses. ",
                                            React.createElement("br", null),
                                            "When you place an order, you provide us with information such as: desired product, first and last name, delivery address, billing details, payment method, phone number, bank card details, etc. "),
                                        React.createElement("h5", null, " 2. What types of personal data do we collect? "),
                                        React.createElement("p", null, " We collect the following personal data for certain purposes and services such as: "),
                                        "- ",
                                        React.createElement("b", null, " first and last name: "),
                                        " In order to deliver the ordered products, we need this data;",
                                        React.createElement("br", null),
                                        " - ",
                                        React.createElement("b", null, " e-mail: "),
                                        " to communicate between the platform and the user, we use the e-mail address to confirm your order and to inform you about the status of orders;",
                                        React.createElement("br", null),
                                        " - ",
                                        React.createElement("b", null, " phone number: "),
                                        " we need the phone number to confirm the order and to establish other details related to the placed order.",
                                        React.createElement("br", null),
                                        " - ",
                                        React.createElement("b", null, " delivery address: "),
                                        " in order to deliver the order, we need to communicate the correct address in the order process",
                                        React.createElement("br", null),
                                        " - ",
                                        React.createElement("b", null, " billing address: "),
                                        " In order to be able to make a tax invoice, we need to communicate the billing information correctly",
                                        React.createElement("br", null),
                                        " - ",
                                        React.createElement("b", null, " order processing and settlement: "),
                                        " processing, validation, settlement or cancellation of orders and / or purchased goods and services.",
                                        React.createElement("br", null),
                                        " - ",
                                        React.createElement("b", null, " money back: "),
                                        " the value of the products according to the existing legal provisions",
                                        React.createElement("br", null),
                                        " - ",
                                        React.createElement("b", null, " refund of products: "),
                                        " return of products according to existing legal provisions",
                                        React.createElement("h5", null, " 3. What is the purpose and basis of the data processing and how do we use your personal information? "),
                                        React.createElement("p", null,
                                            " Data that \"user / client\" offer them to us voluntarily, the ones he sends by placing an order on the legal basis is to take steps at the request of the data subject before concluding a contract (Article 6 (1) (b) of Regulation (EU) 679 / 2016). ",
                                            React.createElement("br", null),
                                            "We use this data to be able to issue a tax invoice and make the correct and proper delivery of the products. "),
                                        React.createElement("p", null, " In this regard, we always ensure that such processing is carried out in compliance with your rights and freedoms, and that the decisions taken on the basis thereof have no legal effect on you and do not affect you in a significant way. Marketing communications are sent with your prior consent. "),
                                        React.createElement("p", null,
                                            " You can also change your mind and withdraw your consent at any time by: ",
                                            React.createElement("br", null),
                                            "- Changing client account settings; ",
                                            React.createElement("br", null),
                                            "- Unsubscribe from messages / emails you receive from us; ",
                                            React.createElement("br", null),
                                            "- Contact gabrielhabet.com. ",
                                            React.createElement("br", null)),
                                        React.createElement("p", null, " There are also certain situations in which we carry out our marketing activities on our legitimate interest to promote and develop our commercial activity, according to Law no. 506/2004, Art.12 (2). In such situations, where we use information about you for our legitimate interest, we intend to take all necessary measures to ensure that your fundamental rights and freedoms are not affected. "),
                                        React.createElement("h5", null, " 4. What is the legal basis for which we collect this personal data? "),
                                        React.createElement("p", null, " The legal basis is to take steps at the request of the data subject by accessing, before concluding a contract (Article 6 (1) (b) of Regulation (EU) 679/2016). "),
                                        React.createElement("p", null, " The data we collect automatically through the use of cookies or other similar technologies, the basis for processing is consent. By accessing the site, you validly give your consent to the processing of the information necessary for its use. "),
                                        React.createElement("h5", null, " 5. Sharing personal data. "),
                                        React.createElement("p", null, " Depending on the case, we may transmit or provide access to certain personal data of yours to the following categories of recipients: DPD courier companies and Fan Curier who ensure the shipment of ordered products. There is also the case that in order to defend a legitimate interest, we may also disclose certain personal data to public authorities. In this regard, we ensure that access to your data by third parties under private law is made on the basis of contracts concluded with them, as specified in the law on data protection and confidentiality of information."),
                                        React.createElement("h5", null, " 6. Retention period of personal data? "),
                                        React.createElement("p", null,
                                            " Personal data is stored while the account on gabrielhabet.com is active. Of course, you can ask us to delete certain data or close your account, depending on your preferences. In the case of orders placed on www.gabrielhabet.com, your personal data, among those that are included in the financial-accounting documents or in documents attached to them, will be kept for 10 years according to the provisions of art. 38 of Annex 1 to Order no. 2634/2015 on financial-accounting documents, issued by the Ministry of Public Finance.",
                                            React.createElement("br", null),
                                            " By default, they will not be accessed for any purpose other than the legal purpose for which they were archived. After 10 years, this data will be destroyed. "),
                                        React.createElement("h5", null, " 7. The rights of the data subject to the collection of personal data. "),
                                        React.createElement("p", null,
                                            " The General Data Protection Regulation gives you a number of rights with regard to the use of your personal data. ",
                                            React.createElement("br", null),
                                            "You can request access to your data, correct mistakes in our files (if any) and / or object to the processing of your personal data. You also have the right to complain to the supervisory authority or to go to court. DIn this case, you may also have the right to request the deletion of your personal data, the right to restrict the processing of your data and the right to data portability. A list of each right can be found below: ",
                                            React.createElement("br", null)),
                                        "- access to personal data",
                                        React.createElement("br", null),
                                        " - rectification of information or personal data",
                                        React.createElement("br", null),
                                        " - deletion of personal data or information. The realization of this right brings with it the elimination of all information about the user and gabrielhabet.com is not guilty of the losses suffered by the user.",
                                        React.createElement("br", null),
                                        " - restriction of personal data",
                                        React.createElement("br", null),
                                        " - portability or opposition of personal data",
                                        React.createElement("br", null),
                                        " - submission complains to the supervisory authority",
                                        React.createElement("h5", null, " 8. Cookies policy. "),
                                        React.createElement("p", null, " As well as being online customers, we appreciate and respect the importance of privacy and data security on the Internet. gabrielhabet.com stores and processes personal data in accordance with the Personal Data Protection Act"),
                                        React.createElement("p", null,
                                            " You can read more about cookies and how to use them: ",
                                            React.createElement("a", { href: "/#/cookie_policy", title: "Cookies" }, " HERE "),
                                            " "),
                                        React.createElement("h5", null, " 9. How can you contact us? "),
                                        React.createElement("p", null, " If you have any questions about our products, you can contact us via the contact form on our website: https://www.gabrielhabet.com/contact, and we will contact you. we will respond as soon as possible. "),
                                        React.createElement("p", null, " You also have the phone number: +40 753 696 163, or often email: contact@gabrielhabet.com for extra questions. "),
                                        React.createElement("p", null, " Facebook page: https://www.facebook.com/butterflygabrielhabet is also at your disposal to efficiently resolve any remaining questions. Remember, from Monday to Friday, between 09:00 and 17:00 you can ask us your questions, and we will be happy to answer you. "),
                                        React.createElement("h5", null, " GDPR privacy policy regarding data processing. "),
                                        " ",
                                        React.createElement("p", null, " "),
                                        React.createElement("p", null,
                                            " ",
                                            React.createElement("a", { href: "https://en-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679&from=EN", target: "_blank" }, " Regulation (EU) 2016/679 "),
                                            " of the European Parliament and of the Council of 27 April 2016 on the protection of individuals with regard to the processing of personal data and on their free movement. gabrielhabet.com considers ensuring the right to the protection of personal data as a fundamental commitment in our collaboration and respects EU regulations. ",
                                            React.createElement("br", null),
                                            " We will try our best to collect and process users' personal data in complete safety. Because we want total transparency in this commitment, we have prepared this page ",
                                            React.createElement("a", { href: "https://www.gabrielhabet/#/privacy_policy" }, " GDPR - Privacy Policy "),
                                            ", to present all the information in as much detail as possible. and transparent, as follows: "),
                                        React.createElement("div", null,
                                            React.createElement("h5", null,
                                                " ",
                                                React.createElement("b", null, " Who we are and how we can be contacted: "),
                                                " "),
                                            React.createElement("div", null,
                                                "- gabrielhabet.com is an online store www.gabrielhabet.com owned by the company GABRIEL HABET SRL, as a legal entity CUI: RO41533477, J22 / 2726/2019 with the field of activity in online commerce. In the collaboration commitment, Gabriel Habet, represents an operator when processing your personal data.",
                                                React.createElement("br", null),
                                                " - For any additional information about GDPR or the quality of operator in the processing of your personal data, please contact us by e-mail: contact@gabrielhabet.com or by phone at: +40 753 696 163"),
                                            React.createElement("h5", null,
                                                " ",
                                                React.createElement("b", null, " What personal information and data we store and process about you: "),
                                                " "),
                                            " ",
                                            React.createElement("p", null, " This personal data is usually collected directly from the user, so you have full or partial control (where technology does not allow us) over the types of information provided. "))),
                                lang == 'it' &&
                                    React.createElement("div", null,
                                        React.createElement("p", null, " Applicando i requisiti delle leggi in vigore n. 677/2001 e 506/2014 sulla tutela delle persone fisiche con riguardo al trattamento dei dati personali e la tutela della privacy nel settore delle comunicazioni elettroniche. Il proprietario, Gabriel Habet SRL con sede legale in Ia\u0219i County, Villageig\u0103na\u0219i Village, \u021Aig\u0103na\u0219i Commune, Main Street, Nr. 126 con numero di matricola nel Registro delle Imprese J22 / 2726/2019, codice fiscale univoco RO41533477 ha l'obbligo di amministrare in condizioni di sicurezza e solo per scopi precisamente specificati i tuoi dati personali che fornisci al momento dell'ordine. "),
                                        React.createElement("p", null,
                                            " Il cliente non \u00E8 obbligato a fornire i dati richiesti, ma questo \u00E8 comunque necessario per completare l'ordine e inserire nuove offerte e sconti dal nostro negozio. Se rifiuti di fornire questi dati, \u00E8 impossibile elaborare e consegnare gli ordini al cliente, il che interrompe il tuo ordine. La modifica o la cancellazione dei dati personali \u00E8 garantita ai sensi della legge n. 677/2001 e l'accesso a queste modifiche si basa sull'utente e sulla password forniti al momento della creazione dell'account. I diritti di opposizione al trattamento dei tuoi dati sono garantiti anche dalla legge, e la richiesta di cancellazione dei dati \u00E8 avanzata dal Titolare, tramite richiesta registrata. ",
                                            React.createElement("br", null),
                                            "Se qualcuno dei tuoi dati non \u00E8 corretto, ti preghiamo di comunicarcelo immediatamente con ogni possibile mezzo di comunicazione. "),
                                        React.createElement("h5", null, " La politica sulla privacy del GDPR relativa al trattamento dei dati include le seguenti informazioni: "),
                                        React.createElement("h5", null, " 1. Cosa sono i dati generali? "),
                                        React.createElement("p", null, " I dati personali sono dati che di solito raccogliamo direttamente da te in modo che tu abbia il controllo sulle informazioni che ci fornisci. "),
                                        React.createElement("p", null,
                                            " Ad esempio, riceviamo informazioni da te come segue: ",
                                            React.createElement("br", null),
                                            "Quando crei un account sul nostro sito web www.gabrielhabet.com, inviaci: indirizzo e-mail. ",
                                            React.createElement("br", null),
                                            "Nella tua sezione personale (Il mio account) puoi aggiungere ulteriori informazioni quali: nome, cognome, numero di telefono, indirizzi di consegna. ",
                                            React.createElement("br", null),
                                            "Quando effettui un ordine, ci fornisci informazioni quali: prodotto desiderato, nome e cognome, indirizzo di consegna, dettagli di fatturazione, metodo di pagamento, numero di telefono, dettagli della carta bancaria, ecc. "),
                                        React.createElement("h5", null, " 2. Quali tipi di dati personali raccogliamo? "),
                                        React.createElement("p", null, " Raccogliamo i seguenti dati personali per determinati scopi e servizi come: "),
                                        "- ",
                                        React.createElement("b", null, " nome e cognome: "),
                                        " per poter consegnare i prodotti ordinati, abbiamo bisogno di questi dati;",
                                        React.createElement("br", null),
                                        "  - ",
                                        React.createElement("b", null, " e-mail: "),
                                        " per comunicare tra la piattaforma e l'utente, utilizziamo l'indirizzo e-mail per confermare il tuo ordine e per informarti sullo stato degli ordini;",
                                        React.createElement("br", null),
                                        "  - ",
                                        React.createElement("b", null, " numero di telefono: "),
                                        " abbiamo bisogno del numero di telefono per confermare l'ordine e per stabilire altri dettagli relativi all'ordine effettuato.",
                                        React.createElement("br", null),
                                        "  - ",
                                        React.createElement("b", null, " indirizzo di consegna: "),
                                        " al fine di consegnare l'ordine, dobbiamo comunicare l'indirizzo corretto nel processo di ordinazione",
                                        React.createElement("br", null),
                                        "  - ",
                                        React.createElement("b", null, " indirizzo di fatturazione: "),
                                        " per presentare correttamente una fattura fiscale, abbiamo bisogno dei dati di fatturazione corretti",
                                        React.createElement("br", null),
                                        "  - ",
                                        React.createElement("b", null, " elaborazione e liquidazione degli ordini: "),
                                        " elaborazione, convalida, liquidazione o annullamento di ordini e / o beni e servizi acquistati.",
                                        React.createElement("br", null),
                                        "  - ",
                                        React.createElement("b", null, " rimborso: "),
                                        " il valore dei prodotti secondo le disposizioni legali esistenti",
                                        React.createElement("br", null),
                                        "  - ",
                                        React.createElement("b", null, " rimborso dei prodotti: "),
                                        " restituzione dei prodotti in base alle disposizioni legali esistenti",
                                        React.createElement("h5", null, " 3. Qual \u00E8 lo scopo e la base del trattamento dei dati e come utilizziamo le tue informazioni personali? "),
                                        React.createElement("p", null,
                                            " I dati che l '\"utente / cliente\" ne offrirli volontariamente, quelli che invia effettuando un ordine sulla base giuridica \u00E8 di prendere provvedimenti su richiesta dell'interessato prima di concludere un contratto (articolo 6 (1) (b) del Regolamento (UE) 679/2016) . ",
                                            React.createElement("br", null),
                                            "Utilizziamo questi dati per poter emettere una fattura fiscale ed effettuare la corretta e corretta consegna dei prodotti. "),
                                        React.createElement("p", null, " A questo proposito, ci assicuriamo sempre che tale trattamento sia effettuato nel rispetto dei tuoi diritti e libert\u00E0 e che le decisioni prese sulla base di ci\u00F2 non abbiano alcun effetto legale su di te e non ti influenzino in modo significativo. Le comunicazioni di marketing vengono inviate previo tuo consenso. "),
                                        React.createElement("p", null,
                                            " Puoi anche cambiare idea e revocare il tuo consenso in qualsiasi momento: ",
                                            React.createElement("br", null),
                                            "- Modifica delle impostazioni dell'account cliente; ",
                                            React.createElement("br", null),
                                            "- Annulla l'iscrizione ai messaggi / e-mail che ricevi da noi; ",
                                            React.createElement("br", null),
                                            "- Contatta gabrielhabet.com. ",
                                            React.createElement("br", null)),
                                        React.createElement("p", null, " Ci sono anche alcune situazioni in cui svolgiamo le nostre attivit\u00E0 di marketing sul nostro legittimo interesse a promuovere e sviluppare la nostra attivit\u00E0 commerciale, ai sensi della Legge n. 506/2004, Art.12 (2). In tali situazioni, in cui utilizziamo le informazioni su di te per il nostro legittimo interesse, intendiamo prendere tutte le misure necessarie per garantire che i tuoi diritti e le tue libert\u00E0 fondamentali non siano pregiudicati. "),
                                        React.createElement("h5", null, " 4. Qual \u00E8 la base giuridica per la quale raccogliamo questi dati personali? "),
                                        React.createElement("p", null, " La base giuridica \u00E8 l'adozione di provvedimenti su richiesta dell'interessato accedendo, prima di concludere un contratto (articolo 6 (1) (b) del Regolamento (UE) 679/2016). "),
                                        React.createElement("p", null, " I dati che raccogliamo automaticamente attraverso l'uso di cookie o altre tecnologie simili, la base per il trattamento \u00E8 il consenso. Accedendo al sito presti validamente il tuo consenso al trattamento delle informazioni necessarie al suo utilizzo. "),
                                        React.createElement("h5", null, " 5. Condivisione dei dati personali. "),
                                        React.createElement("p", null, " A seconda dei casi, potremmo trasmettere o fornire l'accesso a determinati tuoi dati personali alle seguenti categorie di destinatari: corrieri DPD e Fan Curier che garantiscono la spedizione dei prodotti ordinati. C'\u00E8 anche il caso in cui, al fine di difendere un interesse legittimo, potremmo anche divulgare alcuni dati personali ad autorit\u00E0 pubbliche. A tal proposito, garantiamo che l'accesso ai tuoi dati da parte di terzi di diritto privato avvenga sulla base di contratti stipulati con loro, come specificato dalla legge sulla protezione dei dati e sulla riservatezza delle informazioni."),
                                        React.createElement("h5", null, " 6. Periodo di conservazione dei dati personali? "),
                                        React.createElement("p", null,
                                            " I dati personali vengono conservati mentre l'account su gabrielhabet.com \u00E8 attivo. Ovviamente puoi chiederci di cancellare determinati dati o chiudere il tuo account, a seconda delle tue preferenze. Nel caso di ordini effettuati su www.gabrielhabet.com, i Suoi dati personali, tra quelli che rientrano nei documenti finanziario-contabili o nei documenti ad essi allegati, saranno conservati per 10 anni secondo quanto previsto dall'art. 38 dell'Allegato 1 al Decreto n. 2634/2015 sui documenti finanziario-contabili, rilasciato dal Ministero delle Finanze Pubbliche.",
                                            React.createElement("br", null),
                                            " Per impostazione predefinita, non sar\u00E0 possibile accedervi per scopi diversi dallo scopo legale per il quale sono stati archiviati. Dopo 10 anni, questi dati verranno distrutti. "),
                                        React.createElement("h5", null, " 7. I diritti dell'interessato alla raccolta dei dati personali. "),
                                        React.createElement("p", null,
                                            " Il regolamento generale sulla protezione dei dati ti conferisce una serie di diritti in relazione all'uso dei tuoi dati personali. ",
                                            React.createElement("br", null),
                                            "Puoi richiedere l'accesso ai tuoi dati, correggere gli errori nei nostri file (se presenti) e / o opporti al trattamento dei tuoi dati personali. Hai anche il diritto di presentare reclamo all'autorit\u00E0 di controllo o di adire il tribunale. Partire In questo caso, potresti anche avere il diritto di richiedere la cancellazione dei tuoi dati personali, il diritto di limitare il trattamento dei tuoi dati e il diritto alla portabilit\u00E0 dei dati. Di seguito \u00E8 riportato un elenco di ciascun diritto: ",
                                            React.createElement("br", null)),
                                        "- accesso ai dati personali",
                                        React.createElement("br", null),
                                        "   - rettifica delle informazioni o dei dati personali",
                                        React.createElement("br", null),
                                        "   - cancellazione di dati o informazioni personali. La realizzazione di questo diritto porta con s\u00E9 anche l'eliminazione di tutte le informazioni sull'utente e gabrielhabet.com non \u00E8 colpevole delle perdite subite dall'utente.",
                                        React.createElement("br", null),
                                        "   - limitazione dei dati personali",
                                        React.createElement("br", null),
                                        "   - portabilit\u00E0 o opposizione dei dati personali",
                                        React.createElement("br", null),
                                        "   - presentazione reclami all'autorit\u00E0 di controllo",
                                        React.createElement("h5", null, " 8. Politica sui cookie. "),
                                        React.createElement("p", null, " Oltre ad essere clienti online, apprezziamo e rispettiamo l'importanza della privacy e della sicurezza dei dati su Internet. gabrielhabet.com archivia ed elabora i dati personali in conformit\u00E0 con la legge sulla protezione dei dati personali"),
                                        React.createElement("p", null,
                                            " Puoi leggere ulteriori informazioni sui cookie e su come utilizzarli: ",
                                            React.createElement("a", { href: "/#/cookie_policy", title: "Cookies" }, " QUI "),
                                            " "),
                                        React.createElement("h5", null, " 9. Come puoi contattarci? "),
                                        React.createElement("p", null, " Se hai domande sui nostri prodotti, puoi contattarci tramite il modulo di contatto sul nostro sito web: https://www.gabrielhabet.com/contact e ti contatteremo. Ti risponderemo il prima possibile. "),
                                        React.createElement("p", null, " Hai anche il numero di telefono: +40 753 696 163, o spesso scrivi a: contact@gabrielhabet.com per ulteriori domande. "),
                                        React.createElement("p", null, " Pagina Facebook: https://www.facebook.com/butterflygabrielhabet \u00E8 anche a tua disposizione per risolvere in modo efficiente qualsiasi domanda tu possa avere. Ricorda, dal luned\u00EC al venerd\u00EC, dalle 09:00 alle 17:00, puoi farci le tue domande e saremo felici di risponderti. "),
                                        React.createElement("h5", null, " Informativa sulla privacy del GDPR relativa al trattamento dei dati. "),
                                        " ",
                                        React.createElement("p", null, " "),
                                        React.createElement("p", null,
                                            " ",
                                            React.createElement("a", { href: "https://en-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679&from=EN", target: "_blank" }, " Regolamento (UE) 2016/679 "),
                                            " del Parlamento europeo e del Consiglio, del 27 aprile 2016, sulla tutela delle persone fisiche con riguardo al trattamento dei dati personali e sulla loro libera circolazione. gabrielhabet.com considera garantire il diritto alla protezione dei dati personali un impegno fondamentale nella nostra collaborazione e rispetta le normative UE. ",
                                            React.createElement("br", null),
                                            " Cercheremo di fare ogni sforzo per raccogliere e trattare i dati personali degli utenti in completa sicurezza. Poich\u00E9 vogliamo la totale trasparenza in questo impegno, abbiamo preparato questa pagina ",
                                            React.createElement("a", { href: "https://www.gabrielhabet/#/privacy_policy" }, " GDPR - Privacy Policy "),
                                            ", per presentare tutte le informazioni nel modo pi\u00F9 dettagliato possibile. e trasparente, come segue: "),
                                        React.createElement("div", null,
                                            React.createElement("h5", null,
                                                " ",
                                                React.createElement("b", null, " Chi siamo e come possiamo essere contattati: "),
                                                " "),
                                            React.createElement("div", null,
                                                "- gabrielhabet.com \u00E8 un negozio online www.gabrielhabet.com di propriet\u00E0 della societ\u00E0 GABRIEL HABET SRL, in qualit\u00E0 di persona giuridica CUI: RO41533477, J22 / 2726/2019 con il campo di attivit\u00E0 nel commercio online. Nell'impegno di collaborazione, Gabriel Habet, rappresenta un operatore nel trattamento dei dati personali.",
                                                React.createElement("br", null),
                                                " - Per qualsiasi informazione aggiuntiva sul GDPR o sulla qualit\u00E0 dell'operatore nel trattamento dei tuoi dati personali, ti preghiamo di contattarci tramite e-mail: contact@gabrielhabet.com o per telefono al: +40 753 696 163"),
                                            React.createElement("h5", null,
                                                " ",
                                                React.createElement("b", null, " Quali informazioni e dati personali archiviamo ed elaboriamo su di te: "),
                                                " "),
                                            " ",
                                            React.createElement("p", null, " Questi dati personali vengono solitamente raccolti direttamente dall'utente, in modo che tu abbia il controllo totale o parziale (laddove la tecnologia non ci consente) sui tipi di informazioni fornite. "))))))))));
    };
    return PrivacyPolicy;
}(React.Component));
exports.PrivacyPolicy = PrivacyPolicy;
//# sourceMappingURL=PagePrivacyPolicy.js.map