import * as React from 'react';
import { Header } from './Header';
import * as Translate from 'react-translate-component';
import en from './languages/en';
import it from './languages/it';
import ro from './languages/ro';
import { bake_cookie, read_cookie, delete_cookie } from 'sfcookies';

export class TermsAndConditions extends React.Component {
    constructor(props) {
        super(props);

        this.reloadPage = this.reloadPage.bind(this);
    }

    public reloadPage() {
        window.location.reload(false);
    }

    render() {
        var lang = read_cookie('lang')

        return (
            <div>
                <main id="main">
                    <div>

                        <Header reloadPage={this.reloadPage} />
                        <section className="ftco-section contact-section bg-light">
                            <div className="container">
                                <div className="bg-white p-3" style={{ textAlign: 'justify' }}>
                                    <div className="row justify-content-center mb-3 pb-3">
                                        <div className="col-md-12 heading-section text-center">
                                            <h2 className="mb-4">Termeni și condiții</h2>
                                        </div>
                                    </div>

                                    {
                                        lang == 'ro' &&
                                        <div>
                                            <div>
                                                <p><b>1. PRIN UTILIZAREA ȘI VIZUALIZAREA ACESTUI SITE, SUNTEȚI DE ACORD CU TERMENII ȘI CONDIȚIILE COMUNICATE MAI JOS</b><br /></p><p>Accesarea și utilizarea acestui site <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> &nbsp;sunt supuse anumitor condiții de utilizare, iar vizualizarea lui presupune acceptarea în totalitate și de fiecare dată a termenilor și condițiilor sub care sunt furnizate serviciile și produsele noastre.</p>
                                                <p><b>2. DEFINIȚII ȘI TERMENI</b></p><p><a href="https://gabrielhabet.com/"><b>Gabrielhabet.com</b></a> – este denumirea comercială a GABRIEL HABET S.R.L., persoană juridică de naționalitate română, având sediul social în Județul Iași, Sat Țigănași, Comuna Țigănași, Strada Principală, Nr. 126 cu număr de ordine în Registrul Comerțului J22/2726/2019, cod unic de înregistrare fiscală RO41533477 și capital social 100 RON.</p>
                                                <p><b>Adresa web</b>: <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> va fi denumită generic site web <a href="https://gabrielhabet.com/">gabrielhabet.com</a>.</p><p><b>Vânzător</b> –societatea GABRIEL HABET SRL care deține și administrează site-ul <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> ,&nbsp;</p>
                                                <p><b>Cumpărător</b> – persoană fizică / juridică care efectuează pe site-ul <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> o Comandă.</p>
                                                <p><b>Client</b> – persoană fizică / juridică care are acces la conținutul site-ului, prin orice mijloc de comunicare pus la dispoziție de către <a href="https://gabrielhabet.com/">Gabrielhabet.com</a> (electronic, telefonic, etc) &nbsp;și care va crea și utiliza un Cont.</p><p><b>Utilizator</b> – persoană fizică/juridică înregistrată pe Site-ul <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> și care prin crearea Contului, și-a dat acordul cu privire la clauzele din secțiunea Termeni și Condiții.</p>
                                                <p><b>Cont </b>– secțiunea din Site-ul <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> ce este formată dintr-o adresa de e-mail și o parolă care permite Cumpărătorului plasarea Comenzii și care conține informații despre istoricul Clientului/ Utilizatorului în Site (Comenzi, facturi fiscale, Adrese de livrare, Tranzacții, etc.).</p>
                                                <p><b>Comandă</b> – document electronic ce face legătură între Vânzător și Cumpărător, prin care Cumpărătorul transmite Vânzătorului intenția să de a achiziționa Produse de pe Site-ul <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> .</p>
                                                <p><b>Produse/ Bunuri </b> – orice produs menționat în Comandă și care urmează a fi livrat de către Vânzător Cumpărătorului că urmare a Comenzii efectuate de către acesta.</p><p><b>Campanie</b> – acțiunea de a expune în scop comercial, un număr de Produse având o perioada limitată de timp, stabilită de către Vânzător.</p>
                                                <p><b>Contract </b>– este încheiat la momentul lansării comenzii și reprezintă o comandă/factură între Client și Vânzător. Termenii și condițiile acestui Contract devin activi în momentul lansării Comenzii, iar renunțarea la contract se face în conformitate cu prevederile legale pentru contractele încheiate la distanță.</p>
                                                <p><b>Conținut</b>:</p><ul><li>informațiile de pe site-ul <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> care pot fi vizualizate sau accesate prin utilizarea unui echipament electronic;</li>
                                                    <li>conținutul oricărui e-mail trimis Clienților de către Vânzător prin mijloace electronice și/sau orice alt mijloc de comunicare disponibil;</li>
                                                    <li>orice informație comunicată prin orice mijloc de către un angajat al Vânzătorului, Cumpărătorului, conform informațiilor de contactare, specificate sau nu de către acesta;</li>
                                                    <li>informații legate de Produsele și/sau tarifele practicate de Vânzător într-o anumită perioada;</li>
                                                    <li>date referitoare la Vânzător, sau alte date privilegiate ale acestuia.</li></ul>
                                                <p><b>Răspuns </b>– informație scrisă care este transmisă Utilizatorului/Clientului/Cumpărătorului care a adresat o întrebare în secțiunea Opinii, în pagină unui produs.&nbsp;</p>
                                                <p><b>Document</b> – prezențele Termene și Condiții.</p>
                                                <p><b>Tranzacție</b> – încasarea/ rambursarea unei sume provenită din vânzarea unui Produs de către <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> , Cumpărătorului, prin utilizarea serviciilor de Transfer Bancar, indiferent de modalitatea de livrare.</p>
                                                <p><b>3. DOCUMENTE CONTRACTUALE</b></p>
                                                <p>3.1. Prin înregistrarea unei Comenzi pe Site-ul <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a>, Cumpărătorul este de acord cu formă de comunicare (telefonic sau e-mail) prin care Vânzătorul își derulează operațiunile comerciale.</p>
                                                <p>3.2. Notificarea primită de către Cumpărător, după efectuarea Comenzii are rol de informare și nu reprezintă acceptarea Comenzii. Această notificare se face electronic (e-mail) sau telefonic.</p>
                                                <p>3.3. Pentru motive justificate, Vânzătorul își rezervă dreptul de a modifică cantitatea Produselor din Comandă. Dacă modifică cantitatea de Produselor din Comandă va anunță Cumpărătorul la adresa de e-mail sau la numărul de telefon puse la dispoziția Vânzătorului la efectuarea Comenzii și va returna suma achitată(dacă contravaloarea produsului comandat a fost achitată prin Transfer Bancar).</p>
                                                <p>3.4. Contractul se consideră încheiat între Vânzător și Cumpărător în momentul primirii de către Cumpărător de la Vânzător, prin intermediul email-ului sau apelului telefonic a notificării de expediere a Comenzii.</p>
                                                <p>3.5. Documentul și informațiile puse la dispoziție de către Vânzător pe Site vor stă la baza Contractului, în completarea acestuia fiind certificatul de garanție emis de către Vânzător sau un furnizor al acestuia pentru Bunurile achiziționate.</p><p><b>4. COMANDĂ</b></p>
                                                <p>4.1. Cumpărătorul poate efectua Comenzi pe Site-ul www.gabrielhabet.com , prin adăugarea Produselor dorite în coșul de cumpărături, urmând a finaliza Comandă. O dată adăugat Produsul în coșul de cumpărături este disponibil pentru achiziție în măsură disponibilități acestuia în stoc. Adăugarea unui Produs în coșul de cumpărături, dar în lipsa de finalizare a Comenzii, nu atrage după sine înregistrarea unei comenzi, implicit nici rezervarea automată a Produsului respectiv.</p>
                                                <p>Efectuarea plății se va face prin una dintre modalitățile indicate (transfer bancar, ramburs la curier).</p>
                                                <p>4.2. Prin finalizarea Comenzii, Cumpărătorul aprobă că toate datele furnizate, necesare procesului de cumpărare, sunt corecte și complete.</p>
                                                <p>4.3. Prin finalizarea Comenzii, Cumpărătorul aprobă că Vânzătorul poate să îl contacteze, prin orice mijloc disponibil, în orice situație în care este necesară contactarea Cumpărătorului.</p>
                                                <p>4.4. Vânzătorul are dreptul de a anula Comandă efectuată de către Cumpărător, în urmă unei notificări prealabile adresate Cumpărătorului prin email sau telefonic, fără nicio obligație ulterioară a vreunei părți față de cealaltă în cazul în care datele furnizate de către Cumpărător la plasarea Comenzii sunt incomplete și/sau incorecte;</p>
                                                <p>4.5 Comenzile neconfirmate de către Cumpărător, prin care nu putem stabili un contact direct, nu vor fi expediate.</p><p>Atenție: Toate Comenzile vor fi confirmate telefonic sau prin email pentru a se face expediția acestora de către Vânzător.</p>
                                                <p><b>5. LIVRAREA PRODUSELOR</b></p>
                                                <p>Magazinul online <a href="https://gabrielhabet.com/">www.gabrielhabet.com</a> are că scop livrarea produselor în cel mai scurt timp posibil.</p>
                                                <ul><li>Termenul de livrare este de 24 de ore lucrătoare din momentul confirmării comenzii de către noi.</li>
                                                    <li>Pentru comenzile realizate în weekend și în zilele de sărbătoare legală, expedierea coletului se va efectua în prima zi lucrătoare.</li></ul>
                                                <p>Toate informațiile despre livrare vor fi cunoscute de Cumpărător în momentul confirmării Comenzii în funcție de ora și volumul comenzilor existente.</p>
                                                <p>&nbsp; <b>6. RETURNAREA PRODUSELOR</b></p>
                                                <p>În cazul în care Cumpărătorul decide să se retragă din Contract, acesta trebuie să completeze obligatoriu online formularul de retur. Anunțul prind returnarea produsului comandat se poate face prin:</p>
                                                <ul>
                                                    <li>Email: <a href="mailto:contact@gabrielhabet.com">contact@gabrielhabet.com</a></li>
                                                    <li>Telefon:<a href="tel:+40753696163"><Translate content='contact.PhoneValue' /></a><br /></li></ul>
                                                <p>Returul dumneavoastră va fi acceptat doar cu anumite condiții, iar termenul de retur este de 14 zile calendaristice de la primirea coletului conform Ordonanței de urgență 34/2014 privind achiziționarea Produselor la distanță.</p>
                                                <p>Costul de transport ce are în vedere returnarea produsului va fi suportat de către client în totalitate, iar în cazul în care ambalajul sau Produsul au avut de suferit, ne rezervăm dreptul de a nu returna contravaloarea produsului comandat.</p><p>Condiții de retur ce trebuiesc îndeplinite de Cumpărător:</p>
                                                <p>Să ne înștiințați cu cel mult 14 zile calendaristice din momentul primirii comenzii de intenția returului și să livrați produsul către noi:</p>
                                                <ul><li>Să anunțați compania de curierat prin care s-a făcut comandă de înmânarea produsului;</li>
                                                    <li>Produsul returnat nu trebuie să prezinte semne de deteriorare sau de purtare, iar ambalajul să fie cel inițial, împreună cu toate materialele ce au însoțit coletul, intacte;</li>
                                                    <li>Gabrielhabet.com își rezervă dreptul de a refuză sau redirecționa coletul înapoi clientului în cazul în care produsul nu îndeplinește condițiile returului;</li>
                                                    <li>Returnarea directă și fără costuri suplimentare de transport pentru Cumpărător se face doar la Produsele cu defect de fabricație, costul total al returului fiind suportat de Gabrielhabet.com</li></ul>
                                                <p><b>7. PREȚURI ȘI PLĂTI</b></p>
                                                <p>Toate prețurile produselor și costurile livrării care sunt afișate pe site-ul www.gabrielhabet.com sunt finale și conțîn TVA, iar în orice moment al tranzacției dumeavoastră veți ști exact care este prețul final care trebuie achitat pentru comandă efectuată, inclusiv pentru serviciile de transport.</p>
                                                <p>Plățile vor fi efectuate prin card bancar, prin intermediul platformei de plăti online <a href="https://paylike.io/" target="_blank">Paylike</a>;</p>
                                                <p><b>9. DREPTURILE PROPRIETĂȚIi</b></p>
                                                <p>Site-ul <a href="https://www.gabrielhabet.com/">www.gabrielhabet.com</a> și conținutul atribuit acestuia sunt în proprietate și sub dreptul de autor(copyright) al GABRIEL HABET SRL. Folosirea și atribuirea în orice scop a materialelor ( atât text cât și imagini) fără un acord scris din partea Proprietarului este strict interzisă și va fi pedepsită conform legilor în vigoare.</p><p>Orice încălcare sau încărcare de încălcare a drepturilor de autor, poate fi reclamată la adresa de email:  <a href="mailto:contact@gabrielhabet.com">contact@gabrielhabet.com</a> sau în callcenter.<br /></p>
                                                <p><b>10. POLITICI DE CONFIDENȚIALITATE</b></p>
                                                <p>Aplicând cerințele legilor în vigoare nr. 677/2001 și 506/2014 privind protecția persoanelor cu privire la prelucrarea datelor cu caracter personal şi protecţia vieţii private în sectorul comunicaţiilor electronice. Proprietarul are obligația de a administra în condiții de siguranță și numai în scopuri precis specificate datele dumeavoastră personale pe care le furnizați în momentul realizări comenzilor.</p>
                                                <p>Clientul nu este obligat să furnizeze datele cerute, dar acest lucru fiind totuși necesar pentru finalizarea comenzii și plasarea de noi oferte și reduceri din partea magazinului nostru. În cazul în care refuzați să furnizați aceste date, apare imposibilitatea procesării și livrării comenzilor către client, lucru ce oprește comandă dumneavoastră.</p><p>Modificarea sau ștergerea datelor personale este garantată conform legii nr. 677/2001, iar accesul asupra acestor modificări este realizat pe baza de user și parolă predate în momentul realizării contului. Drepturile de opunere asupra prelucrării datelor dumneavoastră sunt la fel garantate prin lege, iar solicitarea ștergerii datelor este realizată de către Proprietar. În momentul în care unele din datele dumeavoastră sunt incorecte va rugăm să ne anunțați imediat prin orice mijloc de comunicare posibil.</p>
                                                <p><b>11. GARANȚIA PRODUSULUI</b></p>
                                                <p>Garanție pentru genți, plicuri, rucsacuri, curele, portofele, accesorii din piele naturală</p><p>GABRIEL HABET SRL, generic denumit Gabrielhabet.com sau www.gabrielhabet.com , în calitate de vânzător asigura calitatea produselor comercializate.</p>
                                                <p>Pentru neconformitatea produsului achiziționat, se acordă garanție 30 de zile de la dată livrării produsului, în conformitate cu prevederile Legii nr. 449/2003 privind vânzarea produselor și garanțiilor asociate acestora și Ordonanței de Guvern nr.21/1992 privind protecția consumatorului.</p>
                                                <p>În cazul lipsei conformității produsului, clientul are dreptul de a-i solicită vânzătorului înlocuirea produsului defect sau restituirea contravalorii acestuia. Termenul de înlocuire a produsului este de maxim 14 zile calendaristice, iar în cazul în care produsul nu se mai află pe stoc, clientul aprobă un termen mai mare de livrare sau acceptă restituirea contravalorii produsului. Toate procedurile de returnare se regăsesc pe site-ul www.gabrielhabet.com și trebuiesc îndeplinite întocmai.</p>
                                                <p>Nu se pot restitui produse care prezintă urme de folosire!</p>
                                                <p>Nu tăiați etichetele produsului. Lipsa etichetelor duce automat la anularea garanției comerciale.</p>
                                                <p>Important! Pentru acordarea garanției trebuiesc respectate toate regulile și condițiile prezentate mai jos:</p>
                                                <ul><li>Gențile, plicurile, rucsacurile sunt destinate exclusiv pentru accesorii și nu pot fi folosite că bagaje de voiaj; Greutatea maximă admisă pentru genți și rucsacuri este de 1-2 kg în funcție de dimensiune, iar pentru plicuri maxim 300 gr;</li>
                                                    <li>Nu încărcați geantă/ rucsacul/ plicul mai mult decât permite volumul acesteia;</li>
                                                    <li>Nu forțați produsele ce conțîn fermoar să se închidă, dacă observați că acestea se închid cu dificultate din cauza supraîncărcării sau din alte motive;</li>
                                                    <li>Feriți produsul de obiecte care pot provoca zgârieturi, arsuri, perforari, sau orice acțiune fizică de natură să îl deterioreze;</li>
                                                    <li>Nu țineți produsul perioada îndelungată în razele solare, ultravioletelor deoarece pot duce la decolorarea și deteriorarea pielii;</li>
                                                    <li>Pentru curățarea petelor se va utiliza o cârpă moale, umezită în apă călduță, în care s-a dizolvat un săpun cu pH neutru;</li>
                                                    <li>Produsele din piele nu se vor depozita lângă sursă de căldură sau în mediu umed și se vor feri de acțiunea produselor petroliere și a solventilor organici;</li>
                                                    <li>Se interzice spălarea sau uscarea produselor în mașînă de spălat, precum și curățarea lor cu alte materiale ce pot provoca deteriorări;</li>
                                                    <li>Intervențiile neautorizate asupra produsului, nerespectarea instrucțiunilor de întreținere, precum și utilizarea acestuia în alt scop decât cel pentru care a fost conceput, conduce la ANULAREA GARANȚIEI.</li></ul>
                                                <p>Garanția se va acordă după constatarea deficiențelor!</p>
                                                <p>Important! Fiecare produs comandat este însoțit de un Certificat de Garanție în care sunt precizate toate condițiile, iar returnarea produsului se face pe baza certificatului de garanție primit.</p><p><br /></p>
                                                <p><b>12. </b><b>Procedura de rezolvare a reclamațiilor:</b></p><ul><li>Orice reclamație poate fi anunțată la adresa de email:  <a href="mailto:contact@gabrielhabet.com">contact@gabrielhabet.com</a> ulterior în cel mai scurt timp posibil, va vom contacta pentru a găși o soluție la situația dumneavoastră.</li><li>Reclamațiile se înregistrează doar printr-un email trimis la  <a href="mailto:contact@gabrielhabet.com">contact@gabrielhabet.com</a> ulterior o să primiți un număr de înregistrare/ de confirmare pe adresa de email prin care faceți cererea.</li></ul>
                                                <p><b>13. GABRIEL HABET - Marca Înregistrată:</b></p><ul><li>Acordat în temeiul Legii Nr 84/1998 privind mărcile și indicațiile geografice pentru marca: "GABRIEL HABET"<b>. </b></li><li>Marca este înregistrată pentru clasele de produse/servicii înscrise în filă de Registrul Mărcilor.<br /></li></ul><p><b><br /></b><br /></p></div>
                                        </div>
                                    }

                                    {
                                        lang == 'en' &&
                                        <div>
                                            <div>
                                                <p> <b> 1. BY USING AND VIEWING THIS SITE, YOU AGREE TO THE TERMS AND CONDITIONS SUBMITTED BELOW </b> <br /> </p> <p> Access to and use of this site <a href="https://gabrielhabet.com/ "> www.gabrielhabet.com </a> &nbsp; are subject to certain terms of use, and viewing them implies full and each time accepting the terms and conditions under which our services and products are provided. </p>
                                                <p> <b> 2. DEFINITIONS AND TERMS </b> </p> <p> <a href="https://gabrielhabet.com/"> <b> Gabrielhabet.com </b> </a> - is the trade name of GABRIEL HABET SRL, legal person of Romanian nationality, having its registered office in Iași County, Țigănași Village, Țigănași Commune, Main Street, Nr. 126 with serial number in the Trade Register J22 / 2726/2019, unique fiscal registration code RO41533477 and share capital 100 RON. </p>
                                                <p> <b> Web address </b>: <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> will be generically referred to as the website <a href="https: //gabrielhabet.com/">gabrielhabet.com </a>. </p> <p> <b> Seller </b> - GABRIEL HABET SRL company that owns and manages the site <a href="https: //gabrielhabet.com/">www.gabrielhabet.com </a>, &nbsp; </p>
                                                <p> <b> Buyer </b> - a natural / legal person who places an Order on <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a>. </p>
                                                <p> <b> Customer </b> - a natural / legal person who has access to the content of the site, through any means of communication provided by <a href="https://gabrielhabet.com/"> Gabrielhabet.com </a> (electronic, telephone, etc.) &nbsp; and who will create and use an Account. </p> <p> <b> User </b> - a natural / legal person registered on the Site <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> and who, by creating the Account, has agreed to the terms of the Terms and Conditions section. </p>
                                                <p> <b> Account </b> - the section of the <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> section that consists of an e-mail address -mail and a password that allows the Buyer to place the Order and that contains information about the history of the Customer / User on the Site (Orders, tax invoices, Delivery addresses, Transactions, etc.). </p>
                                                <p> <b> Order </b> - electronic document linking the Seller and the Buyer, by which the Buyer transmits to the Seller the intention to purchase Products from the Site <a href="https://gabrielhabet.com /">www.gabrielhabet.com </a>. </p>
                                                <p> <b> Products / Goods </b> - any product mentioned in the Order and to be delivered by the Seller to the Buyer as a result of the Order placed by him. </p> <p> <b> Campaign </b> - the act of displaying for commercial purposes a number of Products with a limited period of time, determined by the Seller. </p>
                                                <p> <b> Contract </b> - is concluded at the time of placing the order and represents an order / invoice between the Customer and the Seller. The terms and conditions of this Agreement become active upon the launch of the Order, and the contract is terminated in accordance with the legal provisions for distance contracts. </p>
                                                <p><b>Content</b>:</p><ul> <li> Information on the <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> a> which can be viewed or accessed using electronic equipment; </li>
                                                    <li> the content of any e-mail sent to Customers by the Seller by electronic means and / or any other available means of communication; </li>
                                                    <li> any information communicated by any means by an employee of the Seller, the Buyer, according to the contact information, specified or not by him; </li>
                                                    <li> information related to the Products and / or tariffs charged by the Seller during a certain period; </li>
                                                    <li> data relating to the Seller, or other privileged data of the Seller. </li> </ul>
                                                <p> <b> Answer </b> - written information that is passed to the User / Customer / Buyer who asked a question in the Reviews section, on a product page. &nbsp; </p>
                                                <p> <b> Document </b> - the present Terms and Conditions. </p><p> <b> Transaction </b> - the collection / refund of an amount from the sale of a Product by <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a>, to the Buyer , by using the Bank Transfer services, regardless of the delivery method. </p>
                                                <p> <b> 3. CONTRACTUAL DOCUMENTS </b> </p>
                                                <p> 3.1. By registering an Order on the Site <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a>, the Buyer agrees to the form of communication (telephone or e-mail) by which The seller carries out his commercial operations. </p>
                                                <p> 3.2. The notification received by the Buyer, after the execution of the Order, has the role of information and does not represent the acceptance of the Order. This notification is made electronically (e-mail) or by telephone. </p>
                                                <p> 3.3. For justified reasons, the Seller reserves the right to change the quantity of Products in the Order. If you change the quantity of Products in the Order, it will notify the Buyer at the e-mail address or telephone number provided to the Seller when placing the Order and will return the amount paid (if the value of the ordered product was paid by Bank Transfer). </p>
                                                <p> 3.4. The contract is considered concluded between the Seller and the Buyer upon receipt by the Buyer from the Seller, by email or telephone call of the notification of dispatch of the Order. </p>
                                                <p> 3.5. The document and the information provided by the Seller on the Site will be the basis of the Contract, in addition to which it will be the guarantee certificate issued by the Seller or a supplier thereof for the Purchased Goods. </p> <p> <b> 4. ORDER </b> </p>
                                                <p> 4.1. The Buyer can place Orders on the Website www.gabrielhabet.com, by adding the desired Products in the shopping cart, following to complete the Order. Once added The product in the shopping cart is available for purchase as long as its availability in stock. The addition of a Product to the shopping cart, but in the absence of completion of the Order, does not entail the registration of an order, implicitly also the automatic reservation of the respective Product. </p>
                                                <p> Payment will be made in one of the ways indicated (bank transfer, cash on delivery). </p>
                                                <p> 4.2. By completing the Order, the Buyer agrees that all data provided, necessary for the purchase process, are correct and complete. </p>
                                                <p> 4.3. By completing the Order, the Buyer agrees that the Seller may contact him, by any available means, in any situation where it is necessary to contact the Buyer. </p>
                                                <p> 4.4. The Seller has the right to cancel the Order placed by the Buyer, following a prior notification addressed to the Buyer by email or telephone, without any subsequent obligation of either party to the other if the data provided by the Buyer when placing the Order is incomplete and / or incorrect; </p>
                                                <p> 4.5 Orders not confirmed by the Buyer, through which we cannot establish a direct contact, will not be shipped. </p> <p> Attention: All Orders will be confirmed by phone or email to be shipped by Seller. </p>
                                                <p> <b> 5. PRODUCT DELIVERY </b> </p>
                                                <p> The online store <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> aims to deliver products as soon as possible. </p>
                                                <ul> <li> The delivery time is 24 working hours from the moment of order confirmation by us. </li>
                                                    <li> For orders placed on weekends and public holidays, the package will be shipped on the first business day. </li> </ul>
                                                <p> All delivery information will be known to the Buyer at the time of order confirmation depending on the time and volume of existing orders. </p>
                                                <p> &nbsp; <b> 6. RETURN OF PRODUCTS </b> </p>
                                                <p> If the Buyer decides to withdraw from the Contract, he must complete the return form online. The announcement of the return of the ordered product can be made by: </p><ul>
                                                    <li> Email: <a href="mailto:contact@gabrielhabet.com"> contact@gabrielhabet.com </a> </li>
                                                    <li> Phone: <a href="tel:+40753696163"> <Translate content='contact.PhoneValue' /> </a> <br /> </li> </ul>
                                                <p> Your return will be accepted only under certain conditions, and the return period is 14 calendar days from receipt of the package according to Emergency Ordinance 34/2014 on the purchase of products at a distance. </p>
                                                <p> The shipping cost for the return of the product will be borne by the customer in full, and if the packaging or the product has suffered, we reserve the right not to return the value of the ordered product. </p> < p> Return conditions to be met by the Buyer: </p>
                                                <p> Notify us within 14 calendar days of receiving the return order and deliver the product to us: </p>
                                                <ul> <li> Notify the courier company that ordered the delivery of the product; </li>
                                                    <li> The returned product must not show signs of deterioration or wear, and the packaging must be the original, together with all the materials accompanying the package, intact; </li>
                                                    <li> Gabrielhabet.com reserves the right to refuse or redirect the package back to the customer if the product does not meet the conditions of return; </li>
                                                    <li> The direct return and without additional transport costs for the Buyer is made only for the Products with manufacturing defect, the total cost of the return being borne by Gabrielhabet.com </li> </ul>
                                                <p> <b> 7. PRICES AND PAYMENTS </b> </p>
                                                <p> All product prices and delivery costs that are displayed on www.gabrielhabet.com are final and include VAT, and at any time during your transaction you will know exactly what the final price is to be paid for the order placed, including for transport services. </p>
                                                <p> Payments will be made by credit card via the online payment platform <a href="https://paylike.io/" target="_blank"> Paylike </a>; </p>
                                                <p> <b> 9. PROPERTY RIGHTS </b> </p>
                                                <p> The website <a href="https://www.gabrielhabet.com/"> www.gabrielhabet.com </a> and the content attributed to it are the property and copyright of GABRIEL HABET SRL. The use and assignment for any purpose of the materials (both text and images) without the written consent of the Owner is strictly prohibited and will be punished in accordance with applicable law. </p> <p> Any violation or infringement of copyright author, can be reported to the email address: <a href="mailto:contact@gabrielhabet.com"> contact@gabrielhabet.com </a> or to the call center. <br /> </p>
                                                <p> <b> 10. PRIVACY POLICIES </b> </p>
                                                <p> Applying the requirements of the laws in force no. 677/2001 and 506/2014 on the protection of individuals with regard to the processing of personal data and the protection of privacy in the electronic communications sector. The owner is obliged to manage your personal data that you provide at the time of placing the orders in a safe manner and only for specified purposes. </p>
                                                <p> The customer is not obliged to provide the required data, but this is still necessary to complete the order and place new offers and discounts from our store. If you refuse to provide this data, it is impossible to process and deliver orders to the customer, which stops your order. </p> <p> The modification or deletion of personal data is guaranteed according to law no. 677/2001, and access to these changes is based on the user and password provided at the time of account creation. The rights to oppose the processing of your data are also guaranteed by law, and the request for deletion of data is made by the Owner. If any of your data is incorrect, please notify us immediately by any means of communication possible. </p>
                                                <p> <b> 11. PRODUCT WARRANTY </b> </p>
                                                <p> Pen warranty bags, envelopes, backpacks, belts, wallets, natural leather accessories </p> <p> GABRIEL HABET SRL, generically called Gabrielhabet.com or www.gabrielhabet.com, as a seller ensures the quality of the products sold. </p> 
                                                <p> For the non-conformity of the purchased product, a 30-day warranty is granted from the date of delivery of the product, in accordance with the provisions of Law no. 449/2003 on the sale of products and the guarantees associated with them and Government Ordinance no. 21/1992 on consumer protection. </p>
                                                <p> In case of non-conformity of the product, the customer has the right to request the seller to replace the defective product or refund its value. The term of replacement of the product is of maximum 14 calendar days, and in case the product is no longer in stock, the customer approves a longer delivery term or accepts the return of the value of the product. All return procedures can be found at www.gabrielhabet.com and must be completed exactly. </p>
                                                <p> Cannot return products that show traces of use! </p>
                                                <p> Do not cut product labels. Lack of labels automatically leads to the cancellation of the commercial guarantee. </p>
                                                <p> Important! All the rules and conditions set out below must be followed to grant the guarantee: </p>
                                                <ul> <li> Bags, envelopes, backpacks are intended exclusively for accessories and cannot be used as travel luggage; The maximum weight allowed for bags and backpacks is 1-2 kg depending on the size, and for envelopes maximum 300 gr; </li>
                                                    <li> Do not load the bag / backpack / envelope more than its volume allows; </li>
                                                    <li> Do not force zippered products to close if you notice that they close with difficulty due to overloading or other reasons; </li>
                                                    <li> Protect the product from objects that could cause scratches, burns, punctures, or any physical action that could damage it; </li>
                                                    <li> Do not store the product for a long time in the sun, ultraviolet rays as it may cause discoloration and damage to the skin; </li>
                                                    <li> To clean stains, use a soft cloth dampened in lukewarm water, in which a neutral pH soap has been dissolved; </li>
                                                    <li> Leather products should not be stored near a heat source or in a humid environment and should be protected from the action of petroleum products and organic solvents; </li>
                                                    <li> It is forbidden to wash or dry the products in the washing machine, as well as to clean them with other materials that may cause damage; </li>
                                                    <li> Unauthorized intervention on the product, non-compliance with the maintenance instructions, and its use for any purpose other than that for which it was designed, will void the WARRANTY. </li> </ul>
                                                <p> The guarantee will be given after the deficiencies are found! </p>
                                                <p> Important! Each product ordered is accompanied by a Warranty Certificate which specifies all the conditions and the return of the product is based on the warranty certificate received. </p> <p> <br /> </p>
                                                <p> <b> 12. </b> <b> Complaint Resolution Procedure: </b> </p> <ul> <li> Any complaint can be reported to the email address: <a href="mailto: contact@gabrielhabet.com" > contact@gabrielhabet.com </a> We will contact you as soon as possible to find a solution to your situation. </li> <li> Complaints are only registered by email to <a href="mailto: contact@gabrielhabet.com"> contact@gabrielhabet.com </a> you will then receive a registration / confirmation number at the email address you are requesting. </li> </ul>
                                                <p> <b> 13. GABRIEL HABET - Registered Trademark: </b> </p> <ul> <li> Granted under Law No. 84/1998 on Trademarks and Geographical Indications for the Trademark: "GABRIEL HABET" <b>. </b></li> <li> The trademark is registered for the classes of products / services registered in the tab by the Trademark Register. <br /> </li></ul><p> <b> <br /> </b> <br /> </p> </div>
                                        </div>
                                    }

                                    {
                                        lang == 'it' &&
                                        <div>
                                            <div>
                                                <p> <b> 1. UTILIZZANDO E VISUALIZZANDO QUESTO SITO, ACCETTI I TERMINI E LE CONDIZIONI INDICATI DI SEGUITO </b> <br /> </p> <p> Accesso e utilizzo di questo sito <a href="https://gabrielhabet.com / "> www.gabrielhabet.com </a> &nbsp; sono soggetti a determinati termini di utilizzo e la loro visualizzazione implica la piena accettazione dei termini e delle condizioni in base ai quali vengono forniti i nostri servizi e prodotti. </p>
                                                <p> <b> 2. DEFINIZIONI E TERMINI </b> </p> <p> <a href="https://gabrielhabet.com/"> <b> Gabrielhabet.com </b> </a> - è il nome commerciale di GABRIEL HABET SRL, persona giuridica di nazionalità rumena, con sede legale in Iași County, Țigănași Village, Țigănași Commune, Main Street, Nr. 126 con matricola nel Registro delle Imprese J22 / 2726/2019, codice fiscale univoco RO41533477 e capitale sociale 100 RON. </p>
                                                <p> <b> Indirizzo web </b>: <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> verrà indicato genericamente come il sito web <a href=" https: //gabrielhabet.com/">gabrielhabet.com </a>. </p> <p> <b> Venditore </b> - GABRIEL HABET SRL azienda che possiede e gestisce il sito <a href="https : //gabrielhabet.com/">www.gabrielhabet.com </a>, &nbsp; </p>
                                                <p> <b> Acquirente </b>: una persona fisica / giuridica che effettua un ordine su <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a>. </ p >
                                                <p> <b> Cliente </b> - una persona fisica / giuridica che ha accesso al contenuto del sito, tramite qualsiasi mezzo di comunicazione fornito da <a href="https://gabrielhabet.com/"> Gabrielhabet .com </a> (elettronico, telefonico, ecc.) &nbsp; e che creerà e utilizzerà un account. </p> <p> <b> Utente </b>: una persona fisica / giuridica registrata sul Sito <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> e che, creando l'account, ha accettato i termini della sezione Termini e condizioni. </p>
                                                <p> <b> Account </b> - la sezione della sezione <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> che consiste in un indirizzo e-mail - mail e una password che consenta all'Acquirente di effettuare l'Ordine e che contenga informazioni sulla cronologia del Cliente / Utente sul Sito (Ordini, fatture fiscali, indirizzi di consegna, Transazioni, ecc.). </p>
                                                <p> <b> Ordine </b> - documento elettronico che collega il Venditore e l'Acquirente, mediante il quale l'Acquirente trasmette al Venditore l'intenzione di acquistare Prodotti dal Sito <a >www.gabrielhabet.com </a>. </p>
                                                <p> <b> Prodotti / Beni </b>: qualsiasi prodotto menzionato nell'Ordine e che deve essere consegnato dal Venditore all'Acquirente a seguito dell'Ordine da lui effettuato. </p> <p> <b> Campagna </ b>: l'atto di mostrare a fini commerciali un numero di Prodotti con un periodo di tempo limitato, determinato dal Venditore. </p>
                                                <p> <b> Contratto </b> - viene concluso al momento dell'ordine e rappresenta un ordine / fattura tra il Cliente e il Venditore. I termini e le condizioni del presente Contratto diventano attivi al lancio dell'Ordine e il contratto viene risolto in conformità con le disposizioni legali per i contratti a distanza. </p>
                                                <p><b>Contenuto</b>:</p> <ul> <li> Informazioni su <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> a > a cui è possibile visualizzare o accedere utilizzando apparecchiature elettroniche; </li>
                                                    <li> il contenuto di qualsiasi e-mail inviata ai Clienti dal Venditore tramite mezzi elettronici e / o qualsiasi altro mezzo di comunicazione disponibile; </li>
                                                    <li> qualsiasi informazione comunicata con qualsiasi mezzo da un dipendente del Venditore, l'Acquirente, in base alle informazioni di contatto, specificate o meno da lui; </li>
                                                    <li> informazioni relative ai Prodotti e / o alle tariffe addebitate dal Venditore durante un determinato periodo; </li>
                                                    <li> dati relativi al venditore o altri dati privilegiati del venditore. </li> </ul>
                                                <p> <b> Risposta </b>: informazioni scritte che vengono passate all'utente / cliente / acquirente che ha posto una domanda nella sezione Recensioni, sulla pagina di un prodotto. &nbsp; </p>
                                                <p> <b> Documento </b> - i presenti Termini e condizioni. </p> <p> <b> Transazione </b>: riscossione / rimborso di un importo dalla vendita di un Prodotto da parte di <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> , all'Acquirente, utilizzando i servizi di Bonifico Bancario, indipendentemente dal metodo di consegna. </p>
                                                <p> <b> 3. DOCUMENTI CONTRATTUALI </b> </p>
                                                <p> 3.1. Registrando un Ordine sul Sito <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a>, l'Acquirente accetta la forma di comunicazione (telefono o e-mail) con la quale il il venditore svolge le sue operazioni commerciali. </p>
                                                <p> 3.2. La notifica ricevuta dall'Acquirente, dopo aver effettuato l'Ordine, ha funzione informativa e non rappresenta l'accettazione dell'Ordine. Questa notifica viene effettuata per via elettronica (e-mail) o per telefono. </p>
                                                <p> 3.3. Per giustificati motivi, il Venditore si riserva il diritto di modificare la quantità di Prodotti nell'Ordine. Se modifichi la quantità di Prodotti nell'Ordine, lo notificherà all'Acquirente all'indirizzo e-mail o al numero di telefono fornito al Venditore al momento dell'ordine e restituirà l'importo pagato (se il valore del prodotto ordinato è stato pagato da Bonifico bancario). </p>
                                                <p> 3.4. Il contratto si considera concluso tra il Venditore e l'Acquirente al ricevimento da parte dell'Acquirente da parte del Venditore, tramite e-mail o telefonata, della notifica di spedizione dell'Ordine. </p>
                                                <p> 3.5. Il documento e le informazioni fornite dal Venditore sul Sito costituiranno la base del Contratto, oltre al quale sarà il certificato di garanzia emesso dal Venditore o da un suo fornitore per i Beni Acquistati. </p> <p> <b> 4. ORDINA </b> </p>
                                                <p> 4.1. L'Acquirente può effettuare Ordini sul Sito www.gabrielhabet.com, aggiungendo i Prodotti desiderati al carrello, seguendo per completare l'Ordine. Una volta aggiunto Il prodotto nel carrello è disponibile per l'acquisto purché sia ​​disponibile in magazzino. L'aggiunta di un Prodotto al carrello, ma in mancanza di completamento dell'Ordine, non comporta la registrazione di un ordine, implicitamente anche la prenotazione automatica del rispettivo Prodotto. </p>
                                                <p> Il pagamento verrà effettuato in una delle modalità indicate (bonifico bancario, contrassegno). </p>
                                                <p> 4.2. Completando l'Ordine, l'Acquirente accetta che tutti i dati forniti, necessari per la procedura di acquisto, siano corretti e completi. </p>
                                                <p> 4.3. Completando l'Ordine, l'Acquirente accetta che il Venditore possa contattarlo, con qualsiasi mezzo disponibile, in qualsiasi situazione in cui sia necessario contattare l'Acquirente. </p>
                                                <p> 4.4. Il Venditore ha il diritto di annullare l'Ordine effettuato dall'Acquirente, previa comunicazione indirizzata all'Acquirente tramite e-mail o telefono, senza alcun obbligo successivo di una delle parti nei confronti dell'altra se i dati forniti dall'Acquirente al momento dell'inoltro dell'Ordine sono incompleti e / o errato; </p>
                                                <p> 4.5 Gli ordini non confermati dall'Acquirente, attraverso i quali non possiamo stabilire un contatto diretto, non verranno spediti. </p> <p> Attenzione: Tutti gli Ordini saranno confermati per telefono o e-mail per essere spediti dal Venditore. </p>
                                                <p> <b> 5. CONSEGNA DEL PRODOTTO </b> </p>
                                                <p> Il negozio online <a href="https://gabrielhabet.com/"> www.gabrielhabet.com </a> mira a fornire i prodotti il ​​prima possibile. </p>
                                                <ul> <li> Il tempo di consegna è di 24 ore lavorative dal momento della conferma dell'ordine da parte nostra. </li>
                                                    <li> Per gli ordini effettuati nei fine settimana e nei giorni festivi, il pacco verrà spedito il primo giorno lavorativo. </li> </ul>
                                                <p> Tutte le informazioni sulla consegna saranno note all'Acquirente al momento della conferma dell'ordine a seconda del tempo e del volume degli ordini esistenti. </p>
                                                <p> &nbsp; <b> 6. RESO DEI PRODOTTI </b> </p>
                                                <p> Se l'Acquirente decide di recedere dal Contratto, deve compilare il modulo di reso online. L'annuncio della restituzione del prodotto ordinato può essere effettuato da: </p> <ul>
                                                    <li> E-mail: <a href="mailto:contact@gabrielhabet.com"> contact@gabrielhabet.com </a> </li>
                                                    <li> Telefono: <a href="tel:+40753696163"> <Translate content='contact.PhoneValue' /> </a> <br /> </li> </ul>
                                                <p> Il tuo reso sarà accettato solo a determinate condizioni e il periodo di restituzione è di 14 giorni di calendario dal ricevimento del pacco secondo l'ordinanza di emergenza 34/2014 sull'acquisto di prodotti a distanza. </p>
                                                <p> Il costo di spedizione per la restituzione del prodotto sarà interamente a carico del cliente, e se l'imballaggio o il prodotto ha subito, ci riserviamo il diritto di non restituire il valore del prodotto ordinato. </p> < p> Condizioni di restituzione che devono essere soddisfatte dall'Acquirente: </p>
                                                <p> Avvisaci entro 14 giorni di calendario dalla ricezione dell'ordine di reso e consegnaci il prodotto: </p>
                                                <ul> <li> Avvisare il corriere che ha ordinato la consegna del prodotto; </li>
                                                    <li> Il prodotto restituito non deve presentare segni di danneggiamento o usura, e l'imballo deve essere quello originale, insieme a tutti i materiali che accompagnano il pacco, integro; </li>
                                                    <li> Gabrielhabet.com si riserva il diritto di rifiutare o reindirizzare il pacco al cliente se il prodotto non soddisfa le condizioni di restituzione; </li>
                                                    <li> La restituzione diretta e senza costi di trasporto aggiuntivi per l'Acquirente viene effettuata solo per i Prodotti con difetto di fabbricazione, il costo totale della restituzione è a carico di Gabrielhabet.com </li> </ul>
                                                <p> <b> 7. PREZZI E PAGAMENTI </b> </p>
                                                <p> Tutti i prezzi dei prodotti e i costi di consegna visualizzati su www.gabrielhabet.com sono definitivi e includono l'IVA, e in qualsiasi momento durante la transazione saprai esattamente qual è il prezzo finale da pagare per l'ordine effettuato, incluso per servizi di trasporto. </p>
                                                <p> I pagamenti verranno effettuati con carta di credito tramite la piattaforma di pagamento online <a href="https://paylike.io/" target="_blank"> Paylike </a>; </p>
                                                <p> <b> 9. DIRITTI DI PROPRIETÀ </b> </p>
                                                <p> Il sito <a href="https://www.gabrielhabet.com/"> www.gabrielhabet.com </a> e il contenuto ad esso attribuito sono di proprietà e copyright di GABRIEL HABET SRL. L'uso e la cessione per qualsiasi scopo dei materiali (sia testuali che immagini) senza il consenso scritto del Titolare è severamente vietato e sarà punito secondo le leggi vigenti. </p> <p> Qualsiasi violazione o addebito di violazione dei diritti di autore, può essere segnalato all'indirizzo di posta elettronica: <a href="mailto:contact@gabrielhabet.com"> contact@gabrielhabet.com </a> o al call center. <br /> </ p >
                                                <p> <b> 10. POLITICHE SULLA PRIVACY </b> </p>
                                                <p> Applicando i requisiti delle leggi in vigore n. 677/2001 e 506/2014 sulla tutela delle persone fisiche con riguardo al trattamento dei dati personali e la tutela della privacy nel settore delle comunicazioni elettroniche. Il titolare è obbligato a gestire i tuoi dati personali che fornisci al momento dell'inoltro degli ordini in modo sicuro e solo per scopi specificati. </p>
                                                <p> Il cliente non è obbligato a fornire i dati richiesti, ma ciò è comunque necessario per completare l'ordine e inserire nuove offerte e sconti dal nostro negozio. Se rifiuti di fornire questi dati, è impossibile elaborare e consegnare gli ordini al cliente, il che interrompe il tuo ordine. </p> <p> La modifica o la cancellazione dei dati personali è garantita ai sensi della legge n. 677/2001 e l'accesso a queste modifiche si basa sull'utente e sulla password forniti al momento della creazione dell'account. I diritti di opposizione al trattamento dei tuoi dati sono garantiti anche dalla legge, e la richiesta di cancellazione dei dati è avanzata dal Titolare. Se qualcuno dei tuoi dati non è corretto, ti preghiamo di comunicarcelo immediatamente con qualsiasi mezzo di comunicazione possibile. </p>
                                                <p> <b> 11. GARANZIA DEL PRODOTTO </b> </p>
                                                <p> Garanzia della penna borse, buste, zaini, cinture, portafogli, accessori in pelle naturale </p> <p> GABRIEL HABET SRL, chiamata genericamente Gabrielhabet.com o www.gabrielhabet.com, in quanto venditore garantisce la qualità dei prodotti venduti. </p>
                                                <p> Per la non conformità del prodotto acquistato viene concessa una garanzia di 30 giorni dalla data di consegna del prodotto, secondo quanto previsto dalla Legge n. 449/2003 sulla vendita di prodotti e relative garanzie e Ordinanza governativa n. 21/1992 sulla tutela dei consumatori. </p>
                                                <p> In caso di non conformità del prodotto, il cliente ha il diritto di richiedere al venditore la sostituzione del prodotto difettoso o il rimborso del suo valore. Il termine di sostituzione del prodotto è di massimo 14 giorni di calendario e, nel caso in cui il prodotto non sia più disponibile, il cliente approva un termine di consegna più lungo o accetta la restituzione del valore del prodotto. Tutte le procedure di reso possono essere trovate su www.gabrielhabet.com e devono essere completate esattamente. </p>
                                                <p> Non è possibile restituire prodotti che mostrano tracce di utilizzo! </p>
                                                <p> Non tagliare le etichette dei prodotti. La mancanza di etichette comporta automaticamente l'annullamento della garanzia commerciale. </p>
                                                <p> Importante! Per la concessione della garanzia devono essere rispettate tutte le regole e le condizioni di seguito riportate: </p>
                                                <ul> <li> Borse, buste, zaini sono destinati esclusivamente agli accessori e non possono essere utilizzati come bagaglio da viaggio; Il peso massimo consentito per borse e zaini è di 1-2 kg a seconda delle dimensioni, e per buste massimo 300 gr; </li>
                                                    <li> Non caricare la borsa / zaino / busta più del suo volume consentito; </li>
                                                    <li> Non forzare la chiusura dei prodotti con cerniera se noti che si chiudono con difficoltà a causa del sovraccarico o per altri motivi; </li>
                                                    <li> Proteggi il prodotto da oggetti che potrebbero causare graffi, ustioni, forature o qualsiasi azione fisica che possa danneggiarlo; </li>
                                                    <li> Non conservare il prodotto per lungo tempo al sole, ai raggi ultravioletti in quanto potrebbe causare scolorimento e danni alla pelle; </li>
                                                    <li> Per pulire le macchie, utilizzare un panno morbido inumidito con acqua tiepida, in cui è stato sciolto un sapone a pH neutro; </li>
                                                    <li> I prodotti in pelle non devono essere conservati vicino a una fonte di calore o in un ambiente umido e devono essere protetti dall'azione dei prodotti petroliferi e dei solventi organici; </li>
                                                    <li> È vietato lavare o asciugare i prodotti in lavatrice, nonché pulirli con altri materiali che possano danneggiarli; </li>
                                                    <li> L'intervento non autorizzato sul prodotto, il mancato rispetto delle istruzioni di manutenzione e il suo utilizzo per scopi diversi da quello per cui è stato progettato, invalideranno la GARANZIA. </li> </ul>
                                                <p> La garanzia verrà data dopo che le carenze saranno state riscontrate! </p>
                                                <p> Importante! Ogni prodotto ordinato è accompagnato da un Certificato di Garanzia che specifica tutte le condizioni e la restituzione del prodotto si basa sul certificato di garanzia ricevuto. </p> <p> <br /> </p>
                                                <p> <b> 12. </b> <b> Procedura per la risoluzione dei reclami: </b> </p> <ul> <li> Qualsiasi reclamo può essere segnalato all'indirizzo e-mail: <a href="mailto: contact@gabrielhabet.com"> contatto @ gabrielhabet.com </a> Ti contatteremo il prima possibile per trovare una soluzione alla tua situazione. </li> <li> I reclami vengono registrati solo tramite e-mail a <a href="mailto: contact@gabrielhabet.com "> contact@gabrielhabet.com </a> riceverai quindi un numero di registrazione / conferma all'indirizzo email richiesto. </li> </ul>
                                                <p> <b> 13. GABRIEL HABET - Marchio registrato: </b> </p> <ul> <li> Concesso ai sensi della legge n. 84/1998 sui marchi e le indicazioni geografiche per il marchio: "GABRIEL HABET" <b>. </b> </li> <li> Il marchio è registrato per le classi di prodotti / servizi registrati nella scheda dal Registro dei marchi. <br /> </li></ul> <p> <b> < br /> </ b> <br /> </p> </div>
                                        </div>
                                    }
                                </div>
                            </div>

                        </section>
                    </div>
                </main>


            </div>
        );
    }
}