"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Header_1 = require("./Header");
var Search = /** @class */ (function (_super) {
    __extends(Search, _super);
    function Search() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    Search.prototype.render = function () {
        return (React.createElement("main", { id: "main" },
            React.createElement("div", null,
                React.createElement(Header_1.Header, null),
                React.createElement("div", { className: "hero-wrap hero-bread", style: { backgroundImage: "url('images/background.jpg')" } },
                    React.createElement("div", { className: "container" },
                        React.createElement("div", { className: "row no-gutters slider-text align-items-center justify-content-center" },
                            React.createElement("div", { className: "col-md-9 ftco-animate text-center" },
                                React.createElement("p", { className: "breadcrumbs" },
                                    React.createElement("span", { className: "mr-2" },
                                        React.createElement("a", { href: "index.html" }, "Home")),
                                    " ",
                                    React.createElement("span", null, "Shop")),
                                React.createElement("h1", { className: "mb-0 bread" }, "Shop"))))),
                React.createElement("section", { className: "ftco-section bg-light" },
                    React.createElement("div", { className: "container" },
                        React.createElement("div", { className: "row" },
                            React.createElement("div", { className: "col-md-8 col-lg-10 order-md-last" },
                                React.createElement("div", { className: "row" },
                                    React.createElement("div", { className: "col-sm-12 col-md-12 col-lg-4 d-flex" },
                                        React.createElement("div", { className: "product d-flex flex-column" },
                                            React.createElement("a", { href: "#", className: "img-prod" },
                                                React.createElement("img", { className: "img-fluid", src: "images/product.png", alt: "..." }),
                                                React.createElement("div", { className: "overlay" })),
                                            React.createElement("div", { className: "text py-3 pb-4 px-3" },
                                                React.createElement("div", { className: "d-flex" },
                                                    React.createElement("div", { className: "cat" },
                                                        React.createElement("span", null, "Lifestyle")),
                                                    React.createElement("div", { className: "rating" },
                                                        React.createElement("p", { className: "text-right mb-0" },
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" }))))),
                                                React.createElement("h3", null,
                                                    React.createElement("a", { href: "#" }, "Nike Free RN 2019 iD")),
                                                React.createElement("div", { className: "pricing" },
                                                    React.createElement("p", { className: "price" },
                                                        React.createElement("span", null, "$120.00"))),
                                                React.createElement("p", { className: "bottom-area d-flex px-3" },
                                                    React.createElement("a", { href: "#", className: "add-to-cart text-center py-2 mr-1" },
                                                        React.createElement("span", null,
                                                            "Add to cart ",
                                                            React.createElement("i", { className: "ion-ios-add ml-1" }))),
                                                    React.createElement("a", { href: "#", className: "buy-now text-center py-2" },
                                                        "Buy now",
                                                        React.createElement("span", null,
                                                            React.createElement("i", { className: "ion-ios-cart ml-1" }))))))),
                                    React.createElement("div", { className: "col-sm-12 col-md-12 col-lg-4 d-flex" },
                                        React.createElement("div", { className: "product d-flex flex-column" },
                                            React.createElement("a", { href: "#", className: "img-prod" },
                                                React.createElement("img", { className: "img-fluid", src: "images/product.png", alt: "..." }),
                                                React.createElement("span", { className: "status" }, "50% Off"),
                                                React.createElement("div", { className: "overlay" })),
                                            React.createElement("div", { className: "text py-3 pb-4 px-3" },
                                                React.createElement("div", { className: "d-flex" },
                                                    React.createElement("div", { className: "cat" },
                                                        React.createElement("span", null, "Lifestyle")),
                                                    React.createElement("div", { className: "rating" },
                                                        React.createElement("p", { className: "text-right mb-0" },
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" }))))),
                                                React.createElement("h3", null,
                                                    React.createElement("a", { href: "#" }, "Nike Free RN 2019 iD")),
                                                React.createElement("div", { className: "pricing" },
                                                    React.createElement("p", { className: "price" },
                                                        React.createElement("span", { className: "mr-2 price-dc" }, "$120.00"),
                                                        React.createElement("span", { className: "price-sale" }, "$80.00"))),
                                                React.createElement("p", { className: "bottom-area d-flex px-3" },
                                                    React.createElement("a", { href: "#", className: "add-to-cart text-center py-2 mr-1" },
                                                        React.createElement("span", null,
                                                            "Add to cart ",
                                                            React.createElement("i", { className: "ion-ios-add ml-1" }))),
                                                    React.createElement("a", { href: "#", className: "buy-now text-center py-2" },
                                                        "Buy now",
                                                        React.createElement("span", null,
                                                            React.createElement("i", { className: "ion-ios-cart ml-1" }))))))),
                                    React.createElement("div", { className: "col-sm-12 col-md-12 col-lg-4 d-flex" },
                                        React.createElement("div", { className: "product" },
                                            React.createElement("a", { href: "#", className: "img-prod" },
                                                React.createElement("img", { className: "img-fluid", src: "images/product.png", alt: "..." }),
                                                React.createElement("div", { className: "overlay" })),
                                            React.createElement("div", { className: "text py-3 pb-4 px-3" },
                                                React.createElement("div", { className: "d-flex" },
                                                    React.createElement("div", { className: "cat" },
                                                        React.createElement("span", null, "Lifestyle")),
                                                    React.createElement("div", { className: "rating" },
                                                        React.createElement("p", { className: "text-right mb-0" },
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" }))))),
                                                React.createElement("h3", null,
                                                    React.createElement("a", { href: "#" }, "Nike Free RN 2019 iD")),
                                                React.createElement("div", { className: "pricing" },
                                                    React.createElement("p", { className: "price" },
                                                        React.createElement("span", null, "$120.00"))),
                                                React.createElement("p", { className: "bottom-area d-flex px-3" },
                                                    React.createElement("a", { href: "#", className: "add-to-cart text-center py-2 mr-1" },
                                                        React.createElement("span", null,
                                                            "Add to cart ",
                                                            React.createElement("i", { className: "ion-ios-add ml-1" }))),
                                                    React.createElement("a", { href: "#", className: "buy-now text-center py-2" },
                                                        "Buy now",
                                                        React.createElement("span", null,
                                                            React.createElement("i", { className: "ion-ios-cart ml-1" }))))))),
                                    React.createElement("div", { className: "col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex" },
                                        React.createElement("div", { className: "product" },
                                            React.createElement("a", { href: "#", className: "img-prod" },
                                                React.createElement("img", { className: "img-fluid", src: "images/product.png", alt: "..." }),
                                                React.createElement("div", { className: "overlay" })),
                                            React.createElement("div", { className: "text py-3 pb-4 px-3" },
                                                React.createElement("div", { className: "d-flex" },
                                                    React.createElement("div", { className: "cat" },
                                                        React.createElement("span", null, "Lifestyle")),
                                                    React.createElement("div", { className: "rating" },
                                                        React.createElement("p", { className: "text-right mb-0" },
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" }))))),
                                                React.createElement("h3", null,
                                                    React.createElement("a", { href: "#" }, "Nike Free RN 2019 iD")),
                                                React.createElement("div", { className: "pricing" },
                                                    React.createElement("p", { className: "price" },
                                                        React.createElement("span", null, "$120.00"))),
                                                React.createElement("p", { className: "bottom-area d-flex px-3" },
                                                    React.createElement("a", { href: "#", className: "add-to-cart text-center py-2 mr-1" },
                                                        React.createElement("span", null,
                                                            "Add to cart ",
                                                            React.createElement("i", { className: "ion-ios-add ml-1" }))),
                                                    React.createElement("a", { href: "#", className: "buy-now text-center py-2" },
                                                        "Buy now",
                                                        React.createElement("span", null,
                                                            React.createElement("i", { className: "ion-ios-cart ml-1" }))))))),
                                    React.createElement("div", { className: "col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex" },
                                        React.createElement("div", { className: "product d-flex flex-column" },
                                            React.createElement("a", { href: "#", className: "img-prod" },
                                                React.createElement("img", { className: "img-fluid", src: "images/product.png", alt: "..." }),
                                                React.createElement("div", { className: "overlay" })),
                                            React.createElement("div", { className: "text py-3 pb-4 px-3" },
                                                React.createElement("div", { className: "d-flex" },
                                                    React.createElement("div", { className: "cat" },
                                                        React.createElement("span", null, "Lifestyle")),
                                                    React.createElement("div", { className: "rating" },
                                                        React.createElement("p", { className: "text-right mb-0" },
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" }))))),
                                                React.createElement("h3", null,
                                                    React.createElement("a", { href: "#" }, "Nike Free RN 2019 iD")),
                                                React.createElement("div", { className: "pricing" },
                                                    React.createElement("p", { className: "price" },
                                                        React.createElement("span", null, "$120.00"))),
                                                React.createElement("p", { className: "bottom-area d-flex px-3" },
                                                    React.createElement("a", { href: "#", className: "add-to-cart text-center py-2 mr-1" },
                                                        React.createElement("span", null,
                                                            "Add to cart ",
                                                            React.createElement("i", { className: "ion-ios-add ml-1" }))),
                                                    React.createElement("a", { href: "#", className: "buy-now text-center py-2" },
                                                        "Buy now",
                                                        React.createElement("span", null,
                                                            React.createElement("i", { className: "ion-ios-cart ml-1" }))))))),
                                    React.createElement("div", { className: "col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex" },
                                        React.createElement("div", { className: "product d-flex flex-column" },
                                            React.createElement("a", { href: "#", className: "img-prod" },
                                                React.createElement("img", { className: "img-fluid", src: "images/product.png", alt: "..." }),
                                                React.createElement("span", { className: "status" }, "50% Off"),
                                                React.createElement("div", { className: "overlay" })),
                                            React.createElement("div", { className: "text py-3 pb-4 px-3" },
                                                React.createElement("div", { className: "d-flex" },
                                                    React.createElement("div", { className: "cat" },
                                                        React.createElement("span", null, "Lifestyle")),
                                                    React.createElement("div", { className: "rating" },
                                                        React.createElement("p", { className: "text-right mb-0" },
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" }))))),
                                                React.createElement("h3", null,
                                                    React.createElement("a", { href: "#" }, "Nike Free RN 2019 iD")),
                                                React.createElement("div", { className: "pricing" },
                                                    React.createElement("p", { className: "price" },
                                                        React.createElement("span", { className: "mr-2 price-dc" }, "$120.00"),
                                                        React.createElement("span", { className: "price-sale" }, "$80.00"))),
                                                React.createElement("p", { className: "bottom-area d-flex px-3" },
                                                    React.createElement("a", { href: "#", className: "add-to-cart text-center py-2 mr-1" },
                                                        React.createElement("span", null,
                                                            "Add to cart ",
                                                            React.createElement("i", { className: "ion-ios-add ml-1" }))),
                                                    React.createElement("a", { href: "#", className: "buy-now text-center py-2" },
                                                        "Buy now",
                                                        React.createElement("span", null,
                                                            React.createElement("i", { className: "ion-ios-cart ml-1" }))))))),
                                    React.createElement("div", { className: "col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex" },
                                        React.createElement("div", { className: "product" },
                                            React.createElement("a", { href: "#", className: "img-prod" },
                                                React.createElement("img", { className: "img-fluid", src: "images/product.png", alt: "..." }),
                                                React.createElement("div", { className: "overlay" })),
                                            React.createElement("div", { className: "text py-3 pb-4 px-3" },
                                                React.createElement("div", { className: "d-flex" },
                                                    React.createElement("div", { className: "cat" },
                                                        React.createElement("span", null, "Lifestyle")),
                                                    React.createElement("div", { className: "rating" },
                                                        React.createElement("p", { className: "text-right mb-0" },
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" }))))),
                                                React.createElement("h3", null,
                                                    React.createElement("a", { href: "#" }, "Nike Free RN 2019 iD")),
                                                React.createElement("div", { className: "pricing" },
                                                    React.createElement("p", { className: "price" },
                                                        React.createElement("span", null, "$120.00"))),
                                                React.createElement("p", { className: "bottom-area d-flex px-3" },
                                                    React.createElement("a", { href: "#", className: "add-to-cart text-center py-2 mr-1" },
                                                        React.createElement("span", null,
                                                            "Add to cart ",
                                                            React.createElement("i", { className: "ion-ios-add ml-1" }))),
                                                    React.createElement("a", { href: "#", className: "buy-now text-center py-2" },
                                                        "Buy now",
                                                        React.createElement("span", null,
                                                            React.createElement("i", { className: "ion-ios-cart ml-1" }))))))),
                                    React.createElement("div", { className: "col-sm-12 col-md-12 col-lg-4 ftco-animate d-flex" },
                                        React.createElement("div", { className: "product" },
                                            React.createElement("a", { href: "#", className: "img-prod" },
                                                React.createElement("img", { className: "img-fluid", src: "images/product.png", alt: "..." }),
                                                React.createElement("div", { className: "overlay" })),
                                            React.createElement("div", { className: "text py-3 pb-4 px-3" },
                                                React.createElement("div", { className: "d-flex" },
                                                    React.createElement("div", { className: "cat" },
                                                        React.createElement("span", null, "Lifestyle")),
                                                    React.createElement("div", { className: "rating" },
                                                        React.createElement("p", { className: "text-right mb-0" },
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" })),
                                                            React.createElement("a", { href: "#" },
                                                                React.createElement("span", { className: "ion-ios-star-outline" }))))),
                                                React.createElement("h3", null,
                                                    React.createElement("a", { href: "#" }, "Nike Free RN 2019 iD")),
                                                React.createElement("div", { className: "pricing" },
                                                    React.createElement("p", { className: "price" },
                                                        React.createElement("span", null, "$120.00"))),
                                                React.createElement("p", { className: "bottom-area d-flex px-3" },
                                                    React.createElement("a", { href: "#", className: "add-to-cart text-center py-2 mr-1" },
                                                        React.createElement("span", null,
                                                            "Add to cart ",
                                                            React.createElement("i", { className: "ion-ios-add ml-1" }))),
                                                    React.createElement("a", { href: "#", className: "buy-now text-center py-2" },
                                                        "Buy now",
                                                        React.createElement("span", null,
                                                            React.createElement("i", { className: "ion-ios-cart ml-1" })))))))),
                                React.createElement("div", { className: "row mt-5" },
                                    React.createElement("div", { className: "col text-center" },
                                        React.createElement("div", { className: "block-27" },
                                            React.createElement("ul", null,
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "#" }, "<")),
                                                React.createElement("li", { className: "active" },
                                                    React.createElement("span", null, "1")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "#" }, "2")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "#" }, "3")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "#" }, "4")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "#" }, "5")),
                                                React.createElement("li", null,
                                                    React.createElement("a", { href: "#" }, ">"))))))),
                            React.createElement("div", { className: "col-md-4 col-lg-2" },
                                React.createElement("div", { className: "sidebar" },
                                    React.createElement("div", { className: "sidebar-box-2" },
                                        React.createElement("h2", { className: "heading" }, "Categories"),
                                        React.createElement("div", { className: "fancy-collapse-panel" },
                                            React.createElement("div", { className: "panel-group", id: "accordion", role: "tablist", "aria-multiselectable": "true" },
                                                React.createElement("div", { className: "panel panel-default" },
                                                    React.createElement("div", { className: "panel-heading", role: "tab", id: "headingOne" },
                                                        React.createElement("h4", { className: "panel-title" },
                                                            React.createElement("a", { "data-toggle": "collapse", "data-parent": "#accordion", href: "#collapseOne", "aria-expanded": "true", "aria-controls": "collapseOne" }, "Men's Shoes"))),
                                                    React.createElement("div", { id: "collapseOne", className: "panel-collapse collapse", role: "tabpanel", "aria-labelledby": "headingOne" },
                                                        React.createElement("div", { className: "panel-body" },
                                                            React.createElement("ul", null,
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Sport")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Casual")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Running")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Jordan")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Soccer")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Football")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Lifestyle")))))),
                                                React.createElement("div", { className: "panel panel-default" },
                                                    React.createElement("div", { className: "panel-heading", role: "tab", id: "headingTwo" },
                                                        React.createElement("h4", { className: "panel-title" },
                                                            React.createElement("a", { className: "collapsed", "data-toggle": "collapse", "data-parent": "#accordion", href: "#collapseTwo", "aria-expanded": "false", "aria-controls": "collapseTwo" }, "Women's Shoes"))),
                                                    React.createElement("div", { id: "collapseTwo", className: "panel-collapse collapse", role: "tabpanel", "aria-labelledby": "headingTwo" },
                                                        React.createElement("div", { className: "panel-body" },
                                                            React.createElement("ul", null,
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Sport")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Casual")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Running")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Jordan")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Soccer")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Football")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Lifestyle")))))),
                                                React.createElement("div", { className: "panel panel-default" },
                                                    React.createElement("div", { className: "panel-heading", role: "tab", id: "headingThree" },
                                                        React.createElement("h4", { className: "panel-title" },
                                                            React.createElement("a", { className: "collapsed", "data-toggle": "collapse", "data-parent": "#accordion", href: "#collapseThree", "aria-expanded": "false", "aria-controls": "collapseThree" }, "Accessories"))),
                                                    React.createElement("div", { id: "collapseThree", className: "panel-collapse collapse", role: "tabpanel", "aria-labelledby": "headingThree" },
                                                        React.createElement("div", { className: "panel-body" },
                                                            React.createElement("ul", null,
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Jeans")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "T-Shirt")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Jacket")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Shoes")))))),
                                                React.createElement("div", { className: "panel panel-default" },
                                                    React.createElement("div", { className: "panel-heading", role: "tab", id: "headingFour" },
                                                        React.createElement("h4", { className: "panel-title" },
                                                            React.createElement("a", { className: "collapsed", "data-toggle": "collapse", "data-parent": "#accordion", href: "#collapseFour", "aria-expanded": "false", "aria-controls": "collapseThree" }, "Clothing"))),
                                                    React.createElement("div", { id: "collapseFour", className: "panel-collapse collapse", role: "tabpanel", "aria-labelledby": "headingFour" },
                                                        React.createElement("div", { className: "panel-body" },
                                                            React.createElement("ul", null,
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Jeans")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "T-Shirt")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Jacket")),
                                                                React.createElement("li", null,
                                                                    React.createElement("a", { href: "#" }, "Shoes"))))))))),
                                    React.createElement("div", { className: "sidebar-box-2" },
                                        React.createElement("h2", { className: "heading" }, "Price Range"),
                                        React.createElement("form", { method: "post", className: "product-form-2" },
                                            React.createElement("div", { className: "row" },
                                                React.createElement("div", { className: "col-md-12" },
                                                    React.createElement("div", { className: "form-group" },
                                                        React.createElement("label", { htmlFor: "guests" }, "Price from:"),
                                                        React.createElement("div", { className: "form-field" },
                                                            React.createElement("i", { className: "icon icon-arrow-down3" }),
                                                            React.createElement("select", { name: "people", id: "people", className: "form-control" },
                                                                React.createElement("option", { value: "#" }, "1"),
                                                                React.createElement("option", { value: "#" }, "200"),
                                                                React.createElement("option", { value: "#" }, "300"),
                                                                React.createElement("option", { value: "#" }, "400"),
                                                                React.createElement("option", { value: "#" }, "1000"))))),
                                                React.createElement("div", { className: "col-md-12" },
                                                    React.createElement("div", { className: "form-group" },
                                                        React.createElement("label", { htmlFor: "guests" }, "Price to:"),
                                                        React.createElement("div", { className: "form-field" },
                                                            React.createElement("i", { className: "icon icon-arrow-down3" }),
                                                            React.createElement("select", { name: "people", id: "people", className: "form-control" },
                                                                React.createElement("option", { value: "#" }, "2000"),
                                                                React.createElement("option", { value: "#" }, "4000"),
                                                                React.createElement("option", { value: "#" }, "6000"),
                                                                React.createElement("option", { value: "#" }, "8000"),
                                                                React.createElement("option", { value: "#" }, "10000"))))))))))))))));
    };
    return Search;
}(React.Component));
exports.Search = Search;
//# sourceMappingURL=PageSearch.js.map